Q1

In [1]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\jigar\anaconda3\lib\site-packages (4.9.1)
Requirement already satisfied: trio~=0.17 in c:\users\jigar\anaconda3\lib\site-packages (from selenium) (0.22.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\jigar\anaconda3\lib\site-packages (from selenium) (0.10.2)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\jigar\anaconda3\lib\site-packages (from selenium) (1.26.11)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\jigar\anaconda3\lib\site-packages (from selenium) (2022.9.14)
Requirement already satisfied: sniffio in c:\users\jigar\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: attrs>=19.2.0 in c:\users\jigar\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: cffi>=1.14 in c:\users\jigar\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: outcome in c:\users\jigar\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: sortedcontainers in c:\users\jigar\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: async-generator>=1.9 in c:\users\jigar\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: idna in c:\users\jigar\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in c:\users\jigar\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.1.1)
Requirement already satisfied: wsproto>=0.14 in c:\users\jigar\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\jigar\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\jigar\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\jigar\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [1]:
import selenium
import pandas as pd
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.by import By
import warnings
warnings.filterwarnings('ignore')
import requests
from selenium.common.exceptions import StaleElementReferenceException,NoSuchElementException
import time

In [2]:
driver=webdriver.Chrome(r"C:\Users\Jigar\Downloads\chromedriver_win32")

In [3]:
driver.get ("https://www.naukri.com/hr-recruiter-jobs")

In [4]:
designation=driver.find_element(By.XPATH,'//input[@class="suggestor-input "]')
designation.send_keys("Data science")

In [5]:
search=driver.find_element(By.XPATH,'/html/body/div[1]/div[3]/div[2]/div[1]/div/button/span[1]')
search.click()
time.sleep(2)

In [15]:
job_opening_url=[]
start=0
end=2
for page in range(start,end):
    job=driver.find_elements(By.XPATH,'//a[@class="title ellipsis"]')
    for i in job:
        job_opening_url.append(i.get_attribute('href'))
    next_button=driver.find_elements(By.XPATH,'/html/body/div[1]/div[4]/div/div/section[2]/div[3]/div/a[2]')

In [16]:
job_opening_url

['https://www.naukri.com/job-listings-engineer-ii-data-science-analytics-raytheon-technologies-bangalore-bengaluru-karnataka-4-to-8-years-220623007510',
 'https://www.naukri.com/job-listings-data-science-engineer-augusta-infotech-bangalore-bengaluru-karnataka-1-to-5-years-210623005821',
 'https://www.naukri.com/job-listings-l-d-trainer-python-data-science-data-analytics-ave-promagne-business-solutions-kolkata-mumbai-hyderabad-secunderabad-pune-chennai-ahmedabad-delhi-ncr-bangalore-bengaluru-9-to-12-years-210623903707',
 'https://www.naukri.com/job-listings-data-science-analyst-accenture-solutions-pvt-ltd-bangalore-bengaluru-3-to-5-years-130623911239',
 'https://www.naukri.com/job-listings-ai-and-data-science-engineer-rtwo-healthcare-solutions-llp-bangalore-bengaluru-3-to-8-years-240623500271',
 'https://www.naukri.com/job-listings-data-science-engineer-conneqt-digital-bangalore-bengaluru-4-to-7-years-160623007773',
 'https://www.naukri.com/job-listings-data-modeller-data-science-ml-trh-consultancy-services-mumbai-hyderabad-secunderabad-pune-chennai-bangalore-bengaluru-delhi-ncr-8-to-13-years-310123913258',
 'https://www.naukri.com/job-listings-software-engineer-data-science-epiqsystems-india-private-limited-hyderabad-secunderabad-0-to-1-years-240623905977',
 'https://www.naukri.com/job-listings-senior-manager-data-science-global-red-hat-india-pvt-ltd-bangalore-bengaluru-8-to-13-years-150623908526',
 'https://www.naukri.com/job-listings-senior-manager-data-science-ani-technologies-pvt-ltd-bangalore-bengaluru-6-to-11-years-010922009005',
 'https://www.naukri.com/job-listings-senior-analyst-data-science-dun-bradstreet-information-services-india-private-limited-hyderabad-secunderabad-5-to-8-years-220623501973',
 'https://www.naukri.com/job-listings-senior-lead-consultant-data-science-all-about-it-india-pvt-ltd-kolkata-mumbai-new-delhi-hyderabad-secunderabad-pune-chennai-bangalore-bengaluru-7-to-10-years-210623500302',
 'https://www.naukri.com/job-listings-data-science-analyst-koch-business-solutions-india-private-limited-bangalore-bengaluru-3-to-5-years-160623905741',
 'https://www.naukri.com/job-listings-data-science-senior-analyst-accenture-solutions-pvt-ltd-mumbai-5-to-8-years-150623910560',
 'https://www.naukri.com/job-listings-data-science-ai-ml-professional-zenq-bangalore-bengaluru-5-to-7-years-230623500144',
 'https://www.naukri.com/job-listings-django-data-science-trainer-ave-promagne-noida-mumbai-hyderabad-secunderabad-pune-chennai-gurgaon-gurugram-coimbatore-bangalore-bengaluru-10-to-20-years-040523908335',
 'https://www.naukri.com/job-listings-data-engineer-data-science-consultant-career-infosystem-bangalore-bengaluru-4-to-9-years-230223908465',
 'https://www.naukri.com/job-listings-data-science-intern-zupee-delhi-ncr-0-to-1-years-210623005770',
 'https://www.naukri.com/job-listings-senior-staff-engineer-data-science-nagarro-india-8-to-10-years-190623002594',
 'https://www.naukri.com/job-listings-hiring-data-science-engineers-tata-elxsi-bangalore-tata-elxsi-bangalore-bengaluru-4-to-8-years-100223009130',
 'https://www.naukri.com/job-listings-engineer-ii-data-science-analytics-raytheon-technologies-bangalore-bengaluru-karnataka-4-to-8-years-220623007510',
 'https://www.naukri.com/job-listings-data-science-engineer-augusta-infotech-bangalore-bengaluru-karnataka-1-to-5-years-210623005821',
 'https://www.naukri.com/job-listings-l-d-trainer-python-data-science-data-analytics-ave-promagne-business-solutions-kolkata-mumbai-hyderabad-secunderabad-pune-chennai-ahmedabad-delhi-ncr-bangalore-bengaluru-9-to-12-years-210623903707',
 'https://www.naukri.com/job-listings-data-science-analyst-accenture-solutions-pvt-ltd-bangalore-bengaluru-3-to-5-years-130623911239',
 'https://www.naukri.com/job-listings-ai-and-data-science-engineer-rtwo-healthcare-solutions-llp-bangalore-bengaluru-3-to-8-years-240623500271',
 'https://www.naukri.com/job-listings-data-science-engineer-conneqt-digital-bangalore-bengaluru-4-to-7-years-160623007773',
 'https://www.naukri.com/job-listings-data-modeller-data-science-ml-trh-consultancy-services-mumbai-hyderabad-secunderabad-pune-chennai-bangalore-bengaluru-delhi-ncr-8-to-13-years-310123913258',
 'https://www.naukri.com/job-listings-software-engineer-data-science-epiqsystems-india-private-limited-hyderabad-secunderabad-0-to-1-years-240623905977',
 'https://www.naukri.com/job-listings-senior-manager-data-science-global-red-hat-india-pvt-ltd-bangalore-bengaluru-8-to-13-years-150623908526',
 'https://www.naukri.com/job-listings-senior-manager-data-science-ani-technologies-pvt-ltd-bangalore-bengaluru-6-to-11-years-010922009005',
 'https://www.naukri.com/job-listings-senior-analyst-data-science-dun-bradstreet-information-services-india-private-limited-hyderabad-secunderabad-5-to-8-years-220623501973',
 'https://www.naukri.com/job-listings-senior-lead-consultant-data-science-all-about-it-india-pvt-ltd-kolkata-mumbai-new-delhi-hyderabad-secunderabad-pune-chennai-bangalore-bengaluru-7-to-10-years-210623500302',
 'https://www.naukri.com/job-listings-data-science-analyst-koch-business-solutions-india-private-limited-bangalore-bengaluru-3-to-5-years-160623905741',
 'https://www.naukri.com/job-listings-data-science-senior-analyst-accenture-solutions-pvt-ltd-mumbai-5-to-8-years-150623910560',
 'https://www.naukri.com/job-listings-data-science-ai-ml-professional-zenq-bangalore-bengaluru-5-to-7-years-230623500144',
 'https://www.naukri.com/job-listings-django-data-science-trainer-ave-promagne-noida-mumbai-hyderabad-secunderabad-pune-chennai-gurgaon-gurugram-coimbatore-bangalore-bengaluru-10-to-20-years-040523908335',
 'https://www.naukri.com/job-listings-data-engineer-data-science-consultant-career-infosystem-bangalore-bengaluru-4-to-9-years-230223908465',
 'https://www.naukri.com/job-listings-data-science-intern-zupee-delhi-ncr-0-to-1-years-210623005770',
 'https://www.naukri.com/job-listings-senior-staff-engineer-data-science-nagarro-india-8-to-10-years-190623002594',
 'https://www.naukri.com/job-listings-hiring-data-science-engineers-tata-elxsi-bangalore-tata-elxsi-bangalore-bengaluru-4-to-8-years-100223009130']

In [25]:
name=[]
for url in job_opening_url:
    driver.get(url)
    time.sleep(2)
    try:
        title=driver.find_element(By.XPATH,'//h1[@class="jd-header-title"]')
        name.append(title.text)
    except NoSuchElementException:
        name.append('-')

In [26]:
name

['Engineer II- Data Science & Analytics',
 'Data Science Engineer',
 'L&D Trainer - Python & Data Science/Data Analytics',
 '-',
 'AI and Data Science Engineer',
 'Data Science Engineer',
 'Data Modeller- Data Science/ ML',
 'Software Engineer, Data Science',
 'Senior Manager Data Science Global',
 'Senior Manager-Data Science',
 'Senior Analyst, Data Science',
 'Senior Lead Consultant - Data Science',
 'Data Science Analyst',
 '-',
 'Data Science, AI/ML Professional',
 'Django / Data Science Trainer',
 'Data Engineer/data Science Consultant',
 'Data Science - Intern',
 'Senior Staff Engineer (Data Science)',
 'Hiring Data Science Engineers - Tata Elxsi, Bangalore',
 'Engineer II- Data Science & Analytics',
 'Data Science Engineer',
 'L&D Trainer - Python & Data Science/Data Analytics',
 '-',
 'AI and Data Science Engineer',
 'Data Science Engineer',
 'Data Modeller- Data Science/ ML',
 'Software Engineer, Data Science',
 'Senior Manager Data Science Global',
 'Senior Manager-Data Science',
 'Senior Analyst, Data Science',
 'Senior Lead Consultant - Data Science',
 'Data Science Analyst',
 '-',
 'Data Science, AI/ML Professional',
 'Django / Data Science Trainer',
 'Data Engineer/data Science Consultant',
 'Data Science - Intern',
 'Senior Staff Engineer (Data Science)',
 'Hiring Data Science Engineers - Tata Elxsi, Bangalore']

In [31]:
skill=[]
for url in job_opening_url:
    driver.get(url)
    time.sleep(2)
    try:
        SR=driver.find_element(By.XPATH,'/html/body/div[1]/main/div[2]/div[1]/section[2]/div[4]/div[3]')
        design.append(Sr.text)
    except NoSuchElementException:
        skill.append('-')

In [32]:
skill

['Data Sciencestatistical modelingmachine learningDeep Learningsql',
 'pythonnumpymachine learningtensorflowPandas',
 'Data Analytics',
 '-',
 '-',
 'Data ScienceAzureArtificial IntelligenceAzure Databricksmachine learning',
 'Data ScienceJavaR',
 'Data Science',
 'Machine Learning',
 'Data ScienceRNatural Language ProcessingMachine LearningDeep Learning',
 '-',
 '-',
 'Data Science',
 '-',
 '-',
 'analyticspredictive analyticsTrainer',
 'Data Science',
 'Machine Learning',
 'Data ScienceCloud ArchitectureMachine LearningAWSPython',
 'Big Data Analytics',
 'Data Sciencestatistical modelingmachine learningDeep Learningsql',
 'pythonnumpymachine learningtensorflowPandas',
 'Data Analytics',
 '-',
 '-',
 'Data ScienceAzureArtificial IntelligenceAzure Databricksmachine learning',
 'Data ScienceJavaR',
 'Data Science',
 'Machine Learning',
 'Data ScienceRNatural Language ProcessingMachine LearningDeep Learning',
 '-',
 '-',
 'Data Science',
 '-',
 '-',
 'analyticspredictive analyticsTrainer',
 'Data Science',
 'Machine Learning',
 'Data ScienceCloud ArchitectureMachine LearningAWSPython',
 'Big Data Analytics']

In [27]:
Role=[]
for url in job_opening_url:
    driver.get(url)
    time.sleep(2)
    try:
        rl=driver.find_element(By.XPATH,'//div[@class="dang-inner-html"]/p[2]')
        skill.append(rl.text)
    except NoSuchElementException:
        Role.append('-')

In [28]:
Role

['Responsibilities:',
 'We are looking for a highly motivated data scientist to develop and apply cutting-edge data analytics, visualization and learning methods for data driven R&D.',
 '',
 '-',
 'Responsibilities:',
 'Notice Period: Immediate Joiner (we are looking for a candidate with 4+ years of experience and can join us in June only)',
 '-',
 '-',
 'Desired Skills/Experience',
 'Department/Group: AI',
 '-',
 '-',
 'Georgia Pacific LLC is looking for a Data Science Analyst to join our Decision Analytics team, as part of Koch Global Services (KGS). Decision Analytics is a Center of Excellence (COE) focused entirely on data science, artificial intelligence, machine learning and advanced analytics projects in the commercial space. We are growing our analytics capability and are looking for entrepreneurial minded people who can help us further develop this COE that is creating exceptionally high value to our business.',
 '-',
 'R language 4/5',
 '-',
 'Data Engineer/Data Science Consultant - Business Intelligence Tools',
 'Core Responsibilities:',
 "We're Nagarro.",
 'Skills: Big Data Analytics, distributed systems (MapReduce, Spark, Hive, Kafka, Oozie, Airflow,\nHadoop, HBase, Presto, Flume, Zookeeper, Impala, SQL, Java, Spring, Tomcat, Jenkins,\nREST APIs, JDBC, Hibernate, Power BI, Tableau, Kibana, Grafana.',
 'Responsibilities:',
 'We are looking for a highly motivated data scientist to develop and apply cutting-edge data analytics, visualization and learning methods for data driven R&D.',
 '',
 '-',
 'Responsibilities:',
 'Notice Period: Immediate Joiner (we are looking for a candidate with 4+ years of experience and can join us in June only)',
 '-',
 '-',
 'Desired Skills/Experience',
 'Department/Group: AI',
 '-',
 '-',
 'Georgia Pacific LLC is looking for a Data Science Analyst to join our Decision Analytics team, as part of Koch Global Services (KGS). Decision Analytics is a Center of Excellence (COE) focused entirely on data science, artificial intelligence, machine learning and advanced analytics projects in the commercial space. We are growing our analytics capability and are looking for entrepreneurial minded people who can help us further develop this COE that is creating exceptionally high value to our business.',
 '-',
 'R language 4/5',
 '-',
 'Data Engineer/Data Science Consultant - Business Intelligence Tools',
 'Core Responsibilities:',
 "We're Nagarro.",
 'Skills: Big Data Analytics, distributed systems (MapReduce, Spark, Hive, Kafka, Oozie, Airflow,\nHadoop, HBase, Presto, Flume, Zookeeper, Impala, SQL, Java, Spring, Tomcat, Jenkins,\nREST APIs, JDBC, Hibernate, Power BI, Tableau, Kibana, Grafana.']

In [35]:
location=[]
for url in job_opening_url:
    driver.get(url)
    time.sleep(2)
    try:
        LT=driver.find_element(By.XPATH,'/html/body/div[1]/main/div[2]/div[1]/section[1]/div[1]/div[2]/div[2]/span')
        location.append(LT.text)
    except NoSuchElementException:
        location.append('-')

In [36]:
location

['Hybrid',
 'Bangalore/ Bengaluru,Karnataka( Electronic City )',
 'Kolkata, Mumbai, Hyderabad/Secunderabad, Pune, Chennai, Ahmedabad, Delhi / NCR, Bangalore/Bengaluru',
 '-',
 'Bangalore/Bengaluru',
 'Hybrid',
 'Mumbai, Hyderabad/Secunderabad, Pune, Chennai, Bangalore/Bengaluru, Delhi / NCR',
 'Hybrid',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Hyderabad/Secunderabad',
 'Kolkata, Mumbai, New Delhi, Hyderabad/Secunderabad, Pune, Chennai, Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 '-',
 'Bangalore/Bengaluru',
 'Noida, Mumbai, Hyderabad/Secunderabad, Pune, Chennai, Gurgaon/Gurugram, Coimbatore, Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Delhi / NCR',
 '-',
 'Bangalore/Bengaluru',
 'Hybrid',
 'Bangalore/ Bengaluru,Karnataka( Electronic City )',
 'Kolkata, Mumbai, Hyderabad/Secunderabad, Pune, Chennai, Ahmedabad, Delhi / NCR, Bangalore/Bengaluru',
 '-',
 'Bangalore/Bengaluru',
 'Hybrid',
 'Mumbai, Hyderabad/Secunderabad, Pune, Chennai, Bangalore/Bengaluru, Delhi / NCR',
 'Hybrid',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Hyderabad/Secunderabad',
 'Kolkata, Mumbai, New Delhi, Hyderabad/Secunderabad, Pune, Chennai, Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 '-',
 'Bangalore/Bengaluru',
 'Noida, Mumbai, Hyderabad/Secunderabad, Pune, Chennai, Gurgaon/Gurugram, Coimbatore, Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Delhi / NCR',
 '-',
 'Bangalore/Bengaluru']

In [38]:
company=[]
for url in job_opening_url:
    driver.get(url)
    time.sleep(2)
    try:
        CT=driver.find_element(By.XPATH,'/html/body/div[1]/main/div[2]/div[1]/section[1]/div[1]/div[1]/div')
        company.append(CT.text)
    except NoSuchElementException:
        company.append('-')

In [39]:
company

['Raytheon Technologies3.849 Reviews',
 'Augusta Infotech',
 'AVE-Promagne Business Solutions',
 '-',
 'Rtwo Healthcare Solutions Llp',
 'Conneqt Digital3.75808 Reviews',
 'TRH Consultancy Services',
 'Epiq Systems4.1122 Reviews',
 'Red Hat4.5269 Reviews',
 'Ola3.61720 Reviews',
 'DUN BRADSTREET INFORMATION SERVICES INDIA PRIVATE LIMITED3.6220 Reviews',
 'All About It India4.57 Reviews',
 'Koch Industries3.8261 Reviews',
 '-',
 'Zenq4.273 Reviews',
 'AVE Promagne',
 'Career Infosystem',
 'Zupee3.625 Reviews',
 'Nagarro4.52807 Reviews',
 'Tata Elxsi4.11229 Reviews',
 'Raytheon Technologies3.849 Reviews',
 'Augusta Infotech',
 'AVE-Promagne Business Solutions',
 '-',
 'Rtwo Healthcare Solutions Llp',
 'Conneqt Digital3.75808 Reviews',
 'TRH Consultancy Services',
 'Epiq Systems4.1122 Reviews',
 'Red Hat4.5269 Reviews',
 'Ola3.61720 Reviews',
 'DUN BRADSTREET INFORMATION SERVICES INDIA PRIVATE LIMITED3.6220 Reviews',
 'All About It India4.57 Reviews',
 'Koch Industries3.8261 Reviews',
 '-',
 'Zenq4.273 Reviews',
 'AVE Promagne',
 'Career Infosystem',
 'Zupee3.625 Reviews',
 'Nagarro4.52807 Reviews',
 'Tata Elxsi4.11229 Reviews']

Q 2

In [1]:

import selenium
import pandas as pd
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.by import By
import warnings
warnings.filterwarnings('ignore')
import requests
from selenium.common.exceptions import StaleElementReferenceException,NoSuchElementException
import time

In [2]:
driver=webdriver.Chrome(r"C:\Users\Jigar\Downloads\chromedriver_win32")

In [3]:
driver.get("https://archive.ics.uci.edu/")

In [4]:
dtype=driver.find_element(By.XPATH,'//input[@class="input-bordered input input-sm join-item w-full"]')
dtype.send_keys("AllDataset")

In [5]:
search=driver.find_element(By.XPATH,'//button[@class="btn-primary btn-sm join-item btn"]')
search.click()
time.sleep(2)

In [6]:
dataset_url=[]
start=0
end=1
for page in range(start,end):
    DU=driver.find_elements(By.XPATH,'//a[@class="link-hover link text-xl font-semibold"]')
    for i in DU:
        dataset_url.append(i.get_attribute('href'))

In [9]:
dataset_url

['https://archive.ics.uci.edu/dataset/602/dry+bean+dataset',
 'https://archive.ics.uci.edu/dataset/697/predict+students+dropout+and+academic+success',
 'https://archive.ics.uci.edu/dataset/30/contraceptive+method+choice',
 'https://archive.ics.uci.edu/dataset/43/haberman+s+survival',
 'https://archive.ics.uci.edu/dataset/555/apartment+for+rent+classified',
 'https://archive.ics.uci.edu/dataset/82/post+operative+patient',
 'https://archive.ics.uci.edu/dataset/742/soda',
 'https://archive.ics.uci.edu/dataset/735/cisco+secure+workload+networks+of+computing+hosts',
 'https://archive.ics.uci.edu/dataset/743/maskreminder',
 'https://archive.ics.uci.edu/dataset/386/fma+a+dataset+for+music+analysis']

In [12]:
datasetname=[]
for url in dataset_url:
    driver.get(url)
    time.sleep(2)
    try:
        DN=driver.find_element(By.XPATH,'//h1[@class="text-3xl font-semibold text-primary-content"]')
        datasetname.append(DN.text)
    except NoSuchElementException:
        datasetname.append('-')

In [13]:
datasetname

['Dry Bean Dataset',
 "Predict students' dropout and academic success",
 'Contraceptive Method Choice',
 "Haberman's Survival",
 'Apartment for rent classified',
 'Post-Operative Patient',
 'SoDA',
 'Cisco Secure Workload Networks of Computing Hosts',
 'MaskReminder',
 'FMA: A Dataset For Music Analysis']

In [21]:
Task=[]
for url in dataset_url:
    driver.get(url)
    time.sleep(2)
    try:
        TN=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[1]/div[1]/div[2]/div[2]/div[3]/p')
        Task.append(TN.text)
    except NoSuchElementException:
        Task.append('-')

In [22]:
Task

['Classification',
 'Classification',
 'Classification',
 'Classification',
 'Classification, Regression, Clustering',
 'Classification',
 'Classification',
 'Clustering, Other',
 'Classification',
 'Classification, Clustering']

In [19]:
attributetype=[]
for url in dataset_url:
    driver.get(url)
    time.sleep(2)
    try:
        AT=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[1]/div[1]/div[2]/div[2]/div[4]/p')
        attributetype.append(AT.text)
    except NoSuchElementException:
        attributetype.append('-')

In [20]:
attributetype

['Integer, Real',
 '-',
 'Categorical, Integer',
 'Integer',
 '-',
 'Categorical, Integer',
 '-',
 '-',
 '-',
 'Real']

In [23]:
datatype=[]
for url in dataset_url:
    driver.get(url)
    time.sleep(2)
    try:
        DT=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[1]/div[1]/div[2]/div[2]/div[1]/p')
        datatype.append(DT.text)
    except NoSuchElementException:
        datatype.append('-')

In [24]:
datatype

['Multivariate',
 'Tabular',
 'Multivariate',
 'Multivariate',
 'Multivariate',
 'Multivariate',
 'Time-Series',
 'Sequential, Text, Other',
 'Time-Series',
 'Multivariate, Time-Series']

In [25]:
instance=[]
for url in dataset_url:
    driver.get(url)
    time.sleep(2)
    try:
        NI=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[1]/div[1]/div[2]/div[2]/div[5]/p')
        instance.append(NI.text)
    except NoSuchElementException:
        instance.append('-')

In [26]:
instance

['13611',
 '4424',
 '1473',
 '306',
 '10000',
 '90',
 '1800',
 '1000000',
 '7600',
 '106574']

In [27]:
Attribute=[]
for url in dataset_url:
    driver.get(url)
    time.sleep(2)
    try:
        AB=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[1]/div[1]/div[2]/div[2]/div[6]/p')
        Attribute.append(AB.text)
    except NoSuchElementException:
        Attribute.append('-')

In [28]:
Attribute

['17', '36', '9', '3', '22', '8', '-', '-', '-', '518']

In [31]:
year=[]
for url in dataset_url:
    driver.get(url)
    time.sleep(2)
    try:
        YR=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[1]/div[1]/div[1]/div[2]/h2')
        year.append(YR.text)
    except NoSuchElementException:
        year.append('-')

In [32]:
year

['Donated on 9/13/2020',
 'Donated on 12/12/2021',
 'Donated on 7/6/1997',
 'Donated on 3/3/1999',
 'Donated on 12/25/2019',
 'Donated on 5/31/1993',
 'Donated on 6/19/2022',
 'Donated on 5/15/2022',
 'Donated on 6/19/2022',
 'Donated on 5/23/2017']

Q 7

In [1]:
import selenium
import pandas as pd
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.by import By
import warnings
warnings.filterwarnings('ignore')
import requests
from selenium.common.exceptions import StaleElementReferenceException,NoSuchElementException
import time

In [2]:
driver=webdriver.Chrome(r"C:\Users\Jigar\Downloads\chromedriver_win32")

In [45]:
driver.get("https://www.imdb.com/list/ls095964455")

In [4]:
name=[]

In [43]:
start=0
end=1
for page in range(start,end):
    NT=driver.find_elements(By.XPATH,'//div[@class="lister-item-content"]/h3/a')
    for i in NT:
        name.append(i.text)

In [44]:
name

['Game of Thrones',
 'Game of Thrones',
 'Stranger Things',
 'The Walking Dead',
 '13 Reasons Why',
 'The 100',
 'Orange Is the New Black',
 'Riverdale',
 "Grey's Anatomy",
 'The Flash',
 'Arrow',
 'Money Heist',
 'The Big Bang Theory',
 'Black Mirror',
 'Sherlock',
 'Vikings',
 'Pretty Little Liars',
 'The Vampire Diaries',
 'American Horror Story',
 'Breaking Bad',
 'Lucifer',
 'Supernatural',
 'Prison Break',
 'How to Get Away with Murder',
 'Teen Wolf',
 'The Simpsons',
 'Once Upon a Time',
 'Narcos',
 'Daredevil',
 'Friends',
 'How I Met Your Mother',
 'Suits',
 'Mr. Robot',
 'The Originals',
 'Supergirl',
 'Gossip Girl',
 'Sense8',
 'Gotham',
 'Westworld',
 'Jessica Jones',
 'Modern Family',
 'Rick and Morty',
 'Shadowhunters',
 'The End of the F***ing World',
 'House of Cards',
 'Dark',
 'Elite',
 'Sex Education',
 'Shameless',
 'New Girl',
 'Agents of S.H.I.E.L.D.',
 'You',
 'Dexter',
 'Fear the Walking Dead',
 'Family Guy',
 'The Blacklist',
 'Lost',
 'Peaky Blinders',
 'House',
 'Quantico',
 'Orphan Black',
 'Homeland',
 'Blindspot',
 "DC's Legends of Tomorrow",
 "The Handmaid's Tale",
 'Chilling Adventures of Sabrina',
 'The Good Doctor',
 'Jane the Virgin',
 'Glee',
 'South Park',
 'Brooklyn Nine-Nine',
 'Under the Dome',
 'The Umbrella Academy',
 'True Detective',
 'The OA',
 'Desperate Housewives',
 'Better Call Saul',
 'Bates Motel',
 'The Punisher',
 'Atypical',
 'Dynasty',
 'This Is Us',
 'The Good Place',
 'Iron Fist',
 'The Rain',
 'Mindhunter',
 'Revenge',
 'Luke Cage',
 'Scandal',
 'The Defenders',
 'Big Little Lies',
 'Insatiable',
 'The Mentalist',
 'The Crown',
 'Chernobyl',
 'iZombie',
 'Reign',
 'A Series of Unfortunate Events',
 'Criminal Minds',
 'Scream: The TV Series',
 'The Haunting of Hill House']

In [22]:
yearspan=[]
start=0
end=1
for page in range(start,end):
    YS=driver.find_elements(By.XPATH,'//h3[@class="lister-item-header"]/span[2]')
    for i in YS:
        yearspan.append(i.text)

In [23]:
yearspan

['(2011–2019)',
 '(2016–2024)',
 '(2010–2022)',
 '(2017–2020)',
 '(2014–2020)',
 '(2013–2019)',
 '(2017–2023)',
 '(2005– )',
 '(2014–2023)',
 '(2012–2020)',
 '(2017–2021)',
 '(2007–2019)',
 '(2011– )',
 '(2010–2017)',
 '(2013–2020)',
 '(2010–2017)',
 '(2009–2017)',
 '(2011– )',
 '(2008–2013)',
 '(2016–2021)',
 '(2005–2020)',
 '(2005–2017)',
 '(2014–2020)',
 '(2011–2017)',
 '(1989– )',
 '(2011–2018)',
 '(2015–2017)',
 '(2015–2018)',
 '(1994–2004)',
 '(2005–2014)',
 '(2011–2019)',
 '(2015–2019)',
 '(2013–2018)',
 '(2015–2021)',
 '(2007–2012)',
 '(2015–2018)',
 '(2014–2019)',
 '(2016–2022)',
 '(2015–2019)',
 '(2009–2020)',
 '(2013– )',
 '(2016–2019)',
 '(2017–2019)',
 '(2013–2018)',
 '(2017–2020)',
 '(2018– )',
 '(2019– )',
 '(2011–2021)',
 '(2011–2018)',
 '(2013–2020)',
 '(2018–2024)',
 '(2006–2013)',
 '(2015–2023)',
 '(1999– )',
 '(2013–2023)',
 '(2004–2010)',
 '(2013–2022)',
 '(2004–2012)',
 '(2015–2018)',
 '(2013–2017)',
 '(2011–2020)',
 '(2015–2020)',
 '(2016–2022)',
 '(2017– )',
 '(2018–2020)',
 '(2017– )',
 '(2014–2019)',
 '(2009–2015)',
 '(1997– )',
 '(2013–2021)',
 '(2013–2015)',
 '(2019–2023)',
 '(2014– )',
 '(2016–2019)',
 '(2004–2012)',
 '(2015–2022)',
 '(2013–2017)',
 '(2017–2019)',
 '(2017–2021)',
 '(2017–2022)',
 '(2016–2022)',
 '(2016–2020)',
 '(2017–2018)',
 '(2018–2020)',
 '(2017–2019)',
 '(2011–2015)',
 '(2016–2018)',
 '(2012–2018)',
 '(2017)',
 '(2017–2019)',
 '(2018–2019)',
 '(2008–2015)',
 '(2016–2023)',
 '(2019)',
 '(2015–2019)',
 '(2013–2017)',
 '(2017–2019)',
 '(2005– )',
 '(2015–2019)',
 '(2018)']

In [26]:
Genre=[]
start=0
end=1
for page in range(start,end):
    GN=driver.find_elements(By.XPATH,'//span[@class="genre"]')
    for i in GN:
        Genre.append(i.text)

In [27]:
Genre

['Action, Adventure, Drama',
 'Drama, Fantasy, Horror',
 'Drama, Horror, Thriller',
 'Drama, Mystery, Thriller',
 'Drama, Mystery, Sci-Fi',
 'Comedy, Crime, Drama',
 'Crime, Drama, Mystery',
 'Drama, Romance',
 'Action, Adventure, Drama',
 'Action, Adventure, Crime',
 'Action, Crime, Drama',
 'Comedy, Romance',
 'Drama, Mystery, Sci-Fi',
 'Crime, Drama, Mystery',
 'Action, Adventure, Drama',
 'Drama, Mystery, Romance',
 'Drama, Fantasy, Horror',
 'Drama, Horror, Sci-Fi',
 'Crime, Drama, Thriller',
 'Crime, Drama, Fantasy',
 'Drama, Fantasy, Horror',
 'Action, Crime, Drama',
 'Crime, Drama, Mystery',
 'Action, Drama, Fantasy',
 'Animation, Comedy',
 'Adventure, Fantasy, Romance',
 'Biography, Crime, Drama',
 'Action, Crime, Drama',
 'Comedy, Romance',
 'Comedy, Drama, Romance',
 'Comedy, Drama',
 'Crime, Drama, Thriller',
 'Drama, Fantasy, Horror',
 'Action, Adventure, Drama',
 'Drama, Romance',
 'Drama, Mystery, Sci-Fi',
 'Action, Crime, Drama',
 'Drama, Mystery, Sci-Fi',
 'Action, Crime, Drama',
 'Comedy, Drama, Romance',
 'Animation, Adventure, Comedy',
 'Action, Drama, Fantasy',
 'Adventure, Comedy, Crime',
 'Drama',
 'Crime, Drama, Mystery',
 'Crime, Drama, Thriller',
 'Comedy, Drama',
 'Comedy, Drama',
 'Comedy, Romance',
 'Action, Adventure, Drama',
 'Crime, Drama, Romance',
 'Crime, Drama, Mystery',
 'Drama, Horror, Sci-Fi',
 'Animation, Comedy',
 'Crime, Drama, Mystery',
 'Adventure, Drama, Fantasy',
 'Crime, Drama',
 'Drama, Mystery',
 'Crime, Drama, Mystery',
 'Drama, Sci-Fi, Thriller',
 'Crime, Drama, Mystery',
 'Action, Crime, Drama',
 'Action, Adventure, Drama',
 'Drama, Sci-Fi, Thriller',
 'Drama, Fantasy, Horror',
 'Drama',
 'Comedy',
 'Comedy, Drama, Music',
 'Animation, Comedy',
 'Comedy, Crime',
 'Drama, Mystery, Sci-Fi',
 'Action, Adventure, Comedy',
 'Crime, Drama, Mystery',
 'Drama, Fantasy, Mystery',
 'Comedy, Drama, Mystery',
 'Crime, Drama',
 'Drama, Horror, Mystery',
 'Action, Crime, Drama',
 'Comedy, Drama',
 'Drama',
 'Comedy, Drama, Romance',
 'Comedy, Drama, Fantasy',
 'Action, Adventure, Crime',
 'Drama, Sci-Fi, Thriller',
 'Crime, Drama, Mystery',
 'Drama, Mystery, Thriller',
 'Action, Crime, Drama',
 'Drama, Thriller',
 'Action, Adventure, Crime',
 'Crime, Drama, Mystery',
 'Comedy, Drama, Thriller',
 'Crime, Drama, Mystery',
 'Biography, Drama, History',
 'Drama, History, Thriller',
 'Comedy, Crime, Drama',
 'Drama',
 'Adventure, Comedy, Drama',
 'Crime, Drama, Mystery',
 'Comedy, Crime, Drama',
 'Drama, Horror, Mystery']

In [28]:
runtime=[]
start=0
end=1
for page in range(start,end):
    RT=driver.find_elements(By.XPATH,'//span[@class="runtime"]')
    for i in RT:
        runtime.append(i.text)

In [29]:
runtime

['57 min',
 '51 min',
 '44 min',
 '60 min',
 '43 min',
 '59 min',
 '45 min',
 '41 min',
 '43 min',
 '42 min',
 '70 min',
 '22 min',
 '60 min',
 '88 min',
 '44 min',
 '44 min',
 '43 min',
 '60 min',
 '49 min',
 '42 min',
 '44 min',
 '44 min',
 '43 min',
 '41 min',
 '22 min',
 '60 min',
 '49 min',
 '54 min',
 '22 min',
 '22 min',
 '44 min',
 '49 min',
 '45 min',
 '43 min',
 '42 min',
 '60 min',
 '42 min',
 '62 min',
 '56 min',
 '22 min',
 '23 min',
 '42 min',
 '25 min',
 '51 min',
 '60 min',
 '60 min',
 '45 min',
 '46 min',
 '22 min',
 '45 min',
 '45 min',
 '53 min',
 '44 min',
 '22 min',
 '43 min',
 '44 min',
 '60 min',
 '44 min',
 '42 min',
 '44 min',
 '55 min',
 '42 min',
 '42 min',
 '60 min',
 '60 min',
 '41 min',
 '60 min',
 '44 min',
 '22 min',
 '22 min',
 '43 min',
 '60 min',
 '55 min',
 '60 min',
 '45 min',
 '46 min',
 '45 min',
 '53 min',
 '30 min',
 '42 min',
 '45 min',
 '22 min',
 '55 min',
 '45 min',
 '60 min',
 '44 min',
 '55 min',
 '43 min',
 '50 min',
 '60 min',
 '45 min',
 '43 min',
 '58 min',
 '330 min',
 '42 min',
 '42 min',
 '50 min',
 '42 min',
 '45 min',
 '572 min']

In [30]:
Ratings=[]
start=0
end=1
for page in range(start,end):
    rat=driver.find_elements(By.XPATH,'//div[@class="ipl-rating-star small"]/span[2]')
    for i in rat:
        Ratings.append(i.text)

In [31]:
Ratings

['9.2',
 '8.7',
 '8.1',
 '7.5',
 '7.6',
 '8.1',
 '6.5',
 '7.6',
 '7.5',
 '7.5',
 '8.2',
 '8.2',
 '8.8',
 '9.1',
 '8.5',
 '7.4',
 '7.7',
 '8',
 '9.5',
 '8.1',
 '8.4',
 '8.3',
 '8.1',
 '7.7',
 '8.7',
 '7.7',
 '8.8',
 '8.6',
 '8.9',
 '8.3',
 '8.4',
 '8.5',
 '8.3',
 '6.2',
 '7.5',
 '8.2',
 '7.8',
 '8.5',
 '7.9',
 '8.5',
 '9.1',
 '6.5',
 '8',
 '8.7',
 '8.7',
 '7.3',
 '8.3',
 '8.6',
 '7.8',
 '7.5',
 '7.7',
 '8.7',
 '6.8',
 '8.2',
 '8',
 '8.3',
 '8.8',
 '8.7',
 '6.7',
 '8.3',
 '8.3',
 '7.3',
 '6.8',
 '8.4',
 '7.4',
 '8',
 '7.9',
 '6.8',
 '8.7',
 '8.4',
 '6.5',
 '7.9',
 '8.9',
 '7.8',
 '7.6',
 '9',
 '8.1',
 '8.5',
 '8.2',
 '7.3',
 '8.7',
 '8.2',
 '6.4',
 '6.3',
 '8.6',
 '7.8',
 '7.3',
 '7.7',
 '7.2',
 '8.5',
 '6.5',
 '8.2',
 '8.6',
 '9.4',
 '7.8',
 '7.4',
 '7.8',
 '8.1',
 '7.1',
 '8.6']

In [61]:
votes=[]
start=0
end=1
for page in range(start,end):
    vot=driver.find_elements(By.XPATH,'//div[@class="lister-item-content"]/p[4]/span[2]')
    for i in vot:
        votes.append(i.text)

In [62]:
votes

[]

Q 6

In [26]:

import selenium
import pandas as pd
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.by import By
import warnings
warnings.filterwarnings('ignore')
import requests
from selenium.common.exceptions import StaleElementReferenceException,NoSuchElementException
import time

In [27]:
driver=webdriver.Chrome(r"C:\Users\Jigar\Downloads\chromedriver_win32")

In [28]:
driver.get("https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare")

In [29]:
Book_name=[]

In [31]:
start=0
end=1
for page in range(start,end):
    BN=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[2]')
    for i in BN:
         Book_name.append(i.text)

In [32]:
Book_name

['Da Vinci Code,The',
 'Harry Potter and the Deathly Hallows',
 "Harry Potter and the Philosopher's Stone",
 'Harry Potter and the Order of the Phoenix',
 'Fifty Shades of Grey',
 'Harry Potter and the Goblet of Fire',
 'Harry Potter and the Chamber of Secrets',
 'Harry Potter and the Prisoner of Azkaban',
 'Angels and Demons',
 "Harry Potter and the Half-blood Prince:Children's Edition",
 'Fifty Shades Darker',
 'Twilight',
 'Girl with the Dragon Tattoo,The:Millennium Trilogy',
 'Fifty Shades Freed',
 'Lost Symbol,The',
 'New Moon',
 'Deception Point',
 'Eclipse',
 'Lovely Bones,The',
 'Curious Incident of the Dog in the Night-time,The',
 'Digital Fortress',
 'Short History of Nearly Everything,A',
 'Girl Who Played with Fire,The:Millennium Trilogy',
 'Breaking Dawn',
 'Very Hungry Caterpillar,The:The Very Hungry Caterpillar',
 'Gruffalo,The',
 "Jamie's 30-Minute Meals",
 'Kite Runner,The',
 'One Day',
 'Thousand Splendid Suns,A',
 "Girl Who Kicked the Hornets' Nest,The:Millennium Trilogy",
 "Time Traveler's Wife,The",
 'Atonement',
 "Bridget Jones's Diary:A Novel",
 'World According to Clarkson,The',
 "Captain Corelli's Mandolin",
 'Sound of Laughter,The',
 'Life of Pi',
 'Billy Connolly',
 'Child Called It,A',
 "Gruffalo's Child,The",
 "Angela's Ashes:A Memoir of a Childhood",
 'Birdsong',
 'Northern Lights:His Dark Materials S.',
 'Labyrinth',
 'Harry Potter and the Half-blood Prince',
 'Help,The',
 'Man and Boy',
 'Memoirs of a Geisha',
 "No.1 Ladies' Detective Agency,The:No.1 Ladies' Detective Agency S.",
 'Island,The',
 'PS, I Love You',
 'You are What You Eat:The Plan That Will Change Your Life',
 'Shadow of the Wind,The',
 'Tales of Beedle the Bard,The',
 'Broker,The',
 "Dr. Atkins' New Diet Revolution:The No-hunger, Luxurious Weight Loss P",
 'Subtle Knife,The:His Dark Materials S.',
 'Eats, Shoots and Leaves:The Zero Tolerance Approach to Punctuation',
 "Delia's How to Cook:(Bk.1)",
 'Chocolat',
 'Boy in the Striped Pyjamas,The',
 "My Sister's Keeper",
 'Amber Spyglass,The:His Dark Materials S.',
 'To Kill a Mockingbird',
 'Men are from Mars, Women are from Venus:A Practical Guide for Improvin',
 'Dear Fatty',
 'Short History of Tractors in Ukrainian,A',
 'Hannibal',
 'Lord of the Rings,The',
 'Stupid White Men:...and Other Sorry Excuses for the State of the Natio',
 'Interpretation of Murder,The',
 'Sharon Osbourne Extreme:My Autobiography',
 'Alchemist,The:A Fable About Following Your Dream',
 "At My Mother's Knee ...:and Other Low Joints",
 'Notes from a Small Island',
 'Return of the Naked Chef,The',
 'Bridget Jones: The Edge of Reason',
 "Jamie's Italy",
 'I Can Make You Thin',
 'Down Under',
 'Summons,The',
 'Small Island',
 'Nigella Express',
 'Brick Lane',
 "Memory Keeper's Daughter,The",
 'Room on the Broom',
 'About a Boy',
 'My Booky Wook',
 'God Delusion,The',
 '"Beano" Annual,The',
 'White Teeth',
 'House at Riverton,The',
 'Book Thief,The',
 'Nights of Rain and Stars',
 'Ghost,The',
 'Happy Days with the Naked Chef',
 'Hunger Games,The:Hunger Games Trilogy',
 "Lost Boy,The:A Foster Child's Search for the Love of a Family",
 "Jamie's Ministry of Food:Anyone Can Learn to Cook in 24 Hours"]

In [33]:
Author_name=[]

In [34]:
start=0
end=1
for page in range(start,end):
    AN=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[3]')
    for i in AN:
         Author_name.append(i.text)

In [35]:
Author_name

['Brown, Dan',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'James, E. L.',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'Brown, Dan',
 'Rowling, J.K.',
 'James, E. L.',
 'Meyer, Stephenie',
 'Larsson, Stieg',
 'James, E. L.',
 'Brown, Dan',
 'Meyer, Stephenie',
 'Brown, Dan',
 'Meyer, Stephenie',
 'Sebold, Alice',
 'Haddon, Mark',
 'Brown, Dan',
 'Bryson, Bill',
 'Larsson, Stieg',
 'Meyer, Stephenie',
 'Carle, Eric',
 'Donaldson, Julia',
 'Oliver, Jamie',
 'Hosseini, Khaled',
 'Nicholls, David',
 'Hosseini, Khaled',
 'Larsson, Stieg',
 'Niffenegger, Audrey',
 'McEwan, Ian',
 'Fielding, Helen',
 'Clarkson, Jeremy',
 'Bernieres, Louis de',
 'Kay, Peter',
 'Martel, Yann',
 'Stephenson, Pamela',
 'Pelzer, Dave',
 'Donaldson, Julia',
 'McCourt, Frank',
 'Faulks, Sebastian',
 'Pullman, Philip',
 'Mosse, Kate',
 'Rowling, J.K.',
 'Stockett, Kathryn',
 'Parsons, Tony',
 'Golden, Arthur',
 'McCall Smith, Alexander',
 'Hislop, Victoria',
 'Ahern, Cecelia',
 'McKeith, Gillian',
 'Zafon, Carlos Ruiz',
 'Rowling, J.K.',
 'Grisham, John',
 'Atkins, Robert C.',
 'Pullman, Philip',
 'Truss, Lynne',
 'Smith, Delia',
 'Harris, Joanne',
 'Boyne, John',
 'Picoult, Jodi',
 'Pullman, Philip',
 'Lee, Harper',
 'Gray, John',
 'French, Dawn',
 'Lewycka, Marina',
 'Harris, Thomas',
 'Tolkien, J. R. R.',
 'Moore, Michael',
 'Rubenfeld, Jed',
 'Osbourne, Sharon',
 'Coelho, Paulo',
 "O'Grady, Paul",
 'Bryson, Bill',
 'Oliver, Jamie',
 'Fielding, Helen',
 'Oliver, Jamie',
 'McKenna, Paul',
 'Bryson, Bill',
 'Grisham, John',
 'Levy, Andrea',
 'Lawson, Nigella',
 'Ali, Monica',
 'Edwards, Kim',
 'Donaldson, Julia',
 'Hornby, Nick',
 'Brand, Russell',
 'Dawkins, Richard',
 '0',
 'Smith, Zadie',
 'Morton, Kate',
 'Zusak, Markus',
 'Binchy, Maeve',
 'Harris, Robert',
 'Oliver, Jamie',
 'Collins, Suzanne',
 'Pelzer, Dave',
 'Oliver, Jamie']

In [36]:
Volumes_sold=[]

In [39]:
start=0
end=1
for page in range(start,end):
    VS=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[4]')
    for i in VS:
         Volumes_sold.append(i.text)

In [40]:
Volumes_sold

['5,094,805',
 '4,475,152',
 '4,200,654',
 '4,179,479',
 '3,758,936',
 '3,583,215',
 '3,484,047',
 '3,377,906',
 '3,193,946',
 '2,950,264',
 '2,479,784',
 '2,315,405',
 '2,233,570',
 '2,193,928',
 '2,183,031',
 '2,152,737',
 '2,062,145',
 '2,052,876',
 '2,005,598',
 '1,979,552',
 '1,928,900',
 '1,852,919',
 '1,814,784',
 '1,787,118',
 '1,783,535',
 '1,781,269',
 '1,743,266',
 '1,629,119',
 '1,616,068',
 '1,583,992',
 '1,555,135',
 '1,546,886',
 '1,539,428',
 '1,508,205',
 '1,489,403',
 '1,352,318',
 '1,310,207',
 '1,310,176',
 '1,231,957',
 '1,217,712',
 '1,208,711',
 '1,204,058',
 '1,184,967',
 '1,181,503',
 '1,181,093',
 '1,153,181',
 '1,132,336',
 '1,130,802',
 '1,126,337',
 '1,115,549',
 '1,108,328',
 '1,107,379',
 '1,104,403',
 '1,092,349',
 '1,090,847',
 '1,087,262',
 '1,054,196',
 '1,037,160',
 '1,023,688',
 '1,015,956',
 '1,009,873',
 '1,004,414',
 '1,003,780',
 '1,002,314',
 '998,213',
 '992,846',
 '986,753',
 '986,115',
 '970,509',
 '967,466',
 '963,353',
 '962,515',
 '959,496',
 '956,114',
 '945,640',
 '931,312',
 '925,425',
 '924,695',
 '906,968',
 '905,086',
 '890,847',
 '869,671',
 '869,659',
 '862,602',
 '856,540',
 '845,858',
 '842,535',
 '828,215',
 '820,563',
 '816,907',
 '816,585',
 '815,586',
 '814,370',
 '809,641',
 '808,900',
 '807,311',
 '794,201',
 '792,187',
 '791,507',
 '791,095']

In [41]:
Publisher=[]

In [42]:
start=0
end=1
for page in range(start,end):
    PL=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[5]')
    for i in PL:
         Publisher.append(i.text)

In [43]:
Publisher

['Transworld',
 'Bloomsbury',
 'Bloomsbury',
 'Bloomsbury',
 'Random House',
 'Bloomsbury',
 'Bloomsbury',
 'Bloomsbury',
 'Transworld',
 'Bloomsbury',
 'Random House',
 'Little, Brown Book',
 'Quercus',
 'Random House',
 'Transworld',
 'Little, Brown Book',
 'Transworld',
 'Little, Brown Book',
 'Pan Macmillan',
 'Random House',
 'Transworld',
 'Transworld',
 'Quercus',
 'Little, Brown Book',
 'Penguin',
 'Pan Macmillan',
 'Penguin',
 'Bloomsbury',
 'Hodder & Stoughton',
 'Bloomsbury',
 'Quercus',
 'Random House',
 'Random House',
 'Pan Macmillan',
 'Penguin',
 'Random House',
 'Random House',
 'Canongate',
 'HarperCollins',
 'Orion',
 'Pan Macmillan',
 'HarperCollins',
 'Random House',
 'Scholastic Ltd.',
 'Orion',
 'Bloomsbury',
 'Penguin',
 'HarperCollins',
 'Random House',
 'Little, Brown Book',
 'Headline',
 'HarperCollins',
 'Penguin',
 'Orion',
 'Bloomsbury',
 'Random House',
 'Random House',
 'Scholastic Ltd.',
 'Profile Books Group',
 'Random House',
 'Transworld',
 'Random House Childrens Books G',
 'Hodder & Stoughton',
 'Scholastic Ltd.',
 'Random House',
 'HarperCollins',
 'Random House',
 'Penguin',
 'Random House',
 'HarperCollins',
 'Penguin',
 'Headline',
 'Little, Brown Book',
 'HarperCollins',
 'Transworld',
 'Transworld',
 'Penguin',
 'Pan Macmillan',
 'Penguin',
 'Transworld',
 'Transworld',
 'Random House',
 'Headline',
 'Random House',
 'Transworld',
 'Penguin',
 'Pan Macmillan',
 'Penguin',
 'Hodder & Stoughton',
 'Transworld',
 'D.C. Thomson',
 'Penguin',
 'Pan Macmillan',
 'Transworld',
 'Orion',
 'Random House',
 'Penguin',
 'Scholastic Ltd.',
 'Orion',
 'Penguin']

In [44]:
Genre=[]

In [45]:
start=0
end=1
for page in range(start,end):
    GN=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[6]')
    for i in GN:
         Genre.append(i.text)

In [46]:
Genre

['Crime, Thriller & Adventure',
 "Children's Fiction",
 "Children's Fiction",
 "Children's Fiction",
 'Romance & Sagas',
 "Children's Fiction",
 "Children's Fiction",
 "Children's Fiction",
 'Crime, Thriller & Adventure',
 "Children's Fiction",
 'Romance & Sagas',
 'Young Adult Fiction',
 'Crime, Thriller & Adventure',
 'Romance & Sagas',
 'Crime, Thriller & Adventure',
 'Young Adult Fiction',
 'Crime, Thriller & Adventure',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'Popular Science',
 'Crime, Thriller & Adventure',
 'Young Adult Fiction',
 'Picture Books',
 'Picture Books',
 'Food & Drink: General',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Humour: Collections & General',
 'General & Literary Fiction',
 'Autobiography: General',
 'General & Literary Fiction',
 'Biography: The Arts',
 'Autobiography: General',
 'Picture Books',
 'Autobiography: General',
 'General & Literary Fiction',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'Science Fiction & Fantasy',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Fitness & Diet',
 'General & Literary Fiction',
 "Children's Fiction",
 'Crime, Thriller & Adventure',
 'Fitness & Diet',
 'Young Adult Fiction',
 'Usage & Writing Guides',
 'Food & Drink: General',
 'General & Literary Fiction',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'Popular Culture & Media: General Interest',
 'Autobiography: The Arts',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'Science Fiction & Fantasy',
 'Current Affairs & Issues',
 'Crime, Thriller & Adventure',
 'Autobiography: The Arts',
 'General & Literary Fiction',
 'Autobiography: The Arts',
 'Travel Writing',
 'Food & Drink: General',
 'General & Literary Fiction',
 'National & Regional Cuisine',
 'Fitness & Diet',
 'Travel Writing',
 'Crime, Thriller & Adventure',
 'General & Literary Fiction',
 'Food & Drink: General',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Picture Books',
 'General & Literary Fiction',
 'Autobiography: The Arts',
 'Popular Science',
 "Children's Annuals",
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Food & Drink: General',
 'Young Adult Fiction',
 'Biography: General',
 'Food & Drink: General']

Q 5

In [1]:
import selenium
import pandas as pd
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.by import By
import warnings
warnings.filterwarnings('ignore')
import requests
from selenium.common.exceptions import StaleElementReferenceException,NoSuchElementException
import time

In [2]:

driver=webdriver.Chrome(r"C:\Users\Jigar\Downloads\chromedriver_win32")

In [3]:
driver.get(" https:/www.billboard.com/")

In [7]:
title=driver.find_element(By.XPATH,'/html/body/div[3]/header/div/div[4]/div/div[1]/div[3]/div[1]/div/div/div/form/label/input')
title.send_keys("Hot 100")

In [8]:
search=driver.find_element(By.XPATH,'/html/body/div[3]/header/div/div[4]/div/div[1]/div[3]/div[1]/div/div/div/form/input')
search.click()
time.sleep(2)

In [15]:
name=[]
start=0
end=1
for page in range(start,end):
    tag=driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]/ul/li[4]/ul/li/h3')
    for i in tag:
         name.append(i.text)

In [16]:
name

['Last Night',
 'Fast Car',
 'Calm Down',
 'Flowers',
 'All My Life',
 'Favorite Song',
 'Karma',
 'Kill Bill',
 "Creepin'",
 'Ella Baila Sola',
 'Sure Thing',
 'Anti-Hero',
 'Snooze',
 'Something In The Orange',
 'Die For You',
 'Fukumean',
 'Need A Favor',
 'Cruel Summer',
 'La Bebe',
 'You Proof',
 'Un x100to',
 "Thinkin' Bout Me",
 'Rock And A Hard Place',
 'Cupid',
 'Search & Rescue',
 'Chemical',
 'Eyes Closed',
 'Next Thing You Know',
 'Back To The Moon',
 'Where She Goes',
 'Attention',
 "I'm Good (Blue)",
 'Thought You Should Know',
 'Dance The Night',
 "Dancin' In The Country",
 'Religiously',
 "Boy's A Liar, Pt. 2",
 'Memory Lane',
 'Put It On Da Floor Again',
 'Area Codes',
 'Stand By Me',
 'Rodeo Dr',
 'Tennessee Orange',
 'Bzrp Music Sessions, Vol. 55',
 'Love You Anyway',
 'One Thing At A Time',
 'TQM',
 'Players',
 'Under The Influence',
 'Thank God',
 'Back At It',
 'Bread & Butter',
 'Princess Diana',
 'Bye',
 'Calling',
 'Daylight',
 'What It Is (Block Boy)',
 'Annihilate',
 'Bury Me In Georgia',
 'Ca$h $hit',
 'Self Love',
 'Bottom',
 'It Matters To Her',
 'Dial Drunk',
 'PRC',
 'Por Las Noches',
 'Mourning',
 'Am I Dreaming',
 'Waffle House',
 'See You Again',
 'TQG',
 'Your Heart Or Mine',
 'Peaches & Eggplants',
 'El Azul',
 'You, Me, & Whiskey',
 'IDK NoMore',
 'P Angels',
 'Cowgirls',
 "Baby Don't Hurt Me",
 'Popular',
 'Fight The Feeling',
 'Slut Me Out',
 'Paybach',
 'Plebada',
 'Save Me',
 'Fragil',
 'Jaded',
 'ICU',
 'Truck Bed',
 "Ain't That Some",
 'Shake Sumn',
 'Trustfall',
 'People',
 'Go Crazy',
 'Chanel',
 'Angel, Pt. 1',
 'Girl In Mine',
 'Moonlight',
 'Classy 101',
 'Bluffin']

In [17]:
artist=[]
start=0
end=1
for page in range(start,end):
    AN=driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]/ul/li[4]/ul/li[1]/span')
    for i in AN:
        artist.append(i.text)

In [18]:
artist

['Morgan Wallen',
 'Luke Combs',
 'Rema & Selena Gomez',
 'Miley Cyrus',
 'Lil Durk Featuring J. Cole',
 'Toosii',
 'Taylor Swift Featuring Ice Spice',
 'SZA',
 'Metro Boomin, The Weeknd & 21 Savage',
 'Eslabon Armado X Peso Pluma',
 'Miguel',
 'Taylor Swift',
 'SZA',
 'Zach Bryan',
 'The Weeknd & Ariana Grande',
 'Gunna',
 'Jelly Roll',
 'Taylor Swift',
 'Yng Lvcas x Peso Pluma',
 'Morgan Wallen',
 'Grupo Frontera X Bad Bunny',
 'Morgan Wallen',
 'Bailey Zimmerman',
 'Fifty Fifty',
 'Drake',
 'Post Malone',
 'Ed Sheeran',
 'Jordan Davis',
 'Gunna',
 'Bad Bunny',
 'Doja Cat',
 'David Guetta & Bebe Rexha',
 'Morgan Wallen',
 'Dua Lipa',
 'Tyler Hubbard',
 'Bailey Zimmerman',
 'PinkPantheress & Ice Spice',
 'Old Dominion',
 'Latto Featuring Cardi B',
 'Kali',
 'Lil Durk Featuring Morgan Wallen',
 'Gunna',
 'Megan Moroney',
 'Bizarrap & Peso Pluma',
 'Luke Combs',
 'Morgan Wallen',
 'Fuerza Regida',
 'Coi Leray',
 'Chris Brown',
 'Kane Brown With Katelyn Brown',
 'Gunna',
 'Gunna',
 'Ice Spice & Nicki Minaj',
 'Peso Pluma',
 'Metro Boomin, Swae Lee & NAV Featuring A Boogie Wit da Hoodie',
 'David Kushner',
 'Doechii Featuring Kodak Black',
 'Metro Boomin, Swae Lee, Lil Wayne & Offset',
 'Kane Brown',
 'Gunna',
 'Metro Boomin & Coi Leray',
 'Gunna',
 'Scotty McCreery',
 'Noah Kahan',
 'Peso Pluma X Natanael Cano',
 'Peso Pluma',
 'Post Malone',
 'Metro Boomin, A$AP Rocky & Roisee',
 'Jonas Brothers',
 'Tyler, The Creator Featuring Kali Uchis',
 'Karol G x Shakira',
 'Jon Pardi',
 'Young Nudy Featuring 21 Savage',
 'Junior H x Peso Pluma',
 'Justin Moore & Priscilla Block',
 'Gunna',
 'Gunna',
 'Morgan Wallen Featuring ERNEST',
 'David Guetta, Anne-Marie & Coi Leray',
 'The Weeknd, Playboi Carti & Madonna',
 'Rod Wave',
 'NLE Choppa',
 'Gunna',
 'El Alfa x Peso Pluma',
 'Jelly Roll With Lainey Wilson',
 'Yahritza y Su Esencia x Grupo Frontera',
 'Miley Cyrus',
 'Coco Jones',
 'HARDY',
 'Morgan Wallen',
 'DaBaby',
 'P!nk',
 'Libianca',
 'Gunna',
 'Becky G & Peso Pluma',
 'Kodak Black, NLE Choppa, Jimin, JVKE & Muni Long',
 'Parmalee',
 'Kali Uchis',
 'Feid x Young Miko',
 'Gucci Mane & Lil Baby']

In [19]:
LWRank=[]
start=0
end=1
for page in range(start,end):
    ran=driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]/ul/li[4]/ul/li[7]/ul/li[3]/span')
    for i in ran:
        LWRank.append(i.text)

In [20]:
Rank

['1',
 '3',
 '4',
 '2',
 '5',
 '6',
 '9',
 '7',
 '8',
 '10',
 '11',
 '12',
 '15',
 '14',
 '13',
 '-',
 '19',
 '39',
 '16',
 '21',
 '18',
 '22',
 '25',
 '24',
 '20',
 '23',
 '26',
 '28',
 '-',
 '17',
 '-',
 '31',
 '30',
 '32',
 '34',
 '42',
 '27',
 '36',
 '29',
 '33',
 '41',
 '-',
 '38',
 '37',
 '49',
 '35',
 '40',
 '45',
 '44',
 '50',
 '-',
 '81',
 '52',
 '53',
 '46',
 '56',
 '60',
 '47',
 '64',
 '-',
 '54',
 '-',
 '55',
 '43',
 '57',
 '58',
 '59',
 '51',
 '65',
 '61',
 '62',
 '67',
 '74',
 '63',
 '66',
 '-',
 '-',
 '69',
 '71',
 '72',
 '76',
 '73',
 '-',
 '68',
 '96',
 '83',
 '85',
 '70',
 '89',
 '77',
 '78',
 '82',
 '80',
 '-',
 '79',
 '-',
 '-',
 '90',
 '-',
 '-']

In [21]:
peakrank=[]
start=0
end=1
for page in range(start,end):
    PR=driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]/ul/li[4]/ul/li[7]/ul/li[4]/span')
    for i in PR:
        peakrank.append(i.text)

In [22]:
peakrank

['1',
 '2',
 '3',
 '1',
 '2',
 '5',
 '2',
 '1',
 '3',
 '4',
 '11',
 '1',
 '13',
 '10',
 '1',
 '16',
 '17',
 '18',
 '11',
 '5',
 '5',
 '9',
 '10',
 '17',
 '2',
 '13',
 '19',
 '28',
 '29',
 '8',
 '31',
 '4',
 '7',
 '32',
 '23',
 '36',
 '3',
 '36',
 '13',
 '33',
 '22',
 '42',
 '30',
 '31',
 '15',
 '10',
 '34',
 '9',
 '12',
 '13',
 '51',
 '48',
 '4',
 '53',
 '41',
 '47',
 '57',
 '44',
 '59',
 '60',
 '54',
 '62',
 '49',
 '43',
 '33',
 '28',
 '36',
 '51',
 '57',
 '44',
 '7',
 '67',
 '73',
 '55',
 '66',
 '76',
 '77',
 '40',
 '71',
 '43',
 '16',
 '28',
 '83',
 '68',
 '85',
 '69',
 '56',
 '63',
 '89',
 '11',
 '69',
 '82',
 '80',
 '94',
 '55',
 '65',
 '97',
 '80',
 '99',
 '100']

In [25]:
weekonboard=[]
start=0
end=1
for page in range(start,end):
    WB=driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]/ul/li[4]/ul/li[7]/ul/li[5]/span')
    for i in WB:
        weekonboard.append(i.text)

In [26]:
weekonboard

['21',
 '13',
 '42',
 '23',
 '6',
 '18',
 '15',
 '28',
 '29',
 '14',
 '47',
 '35',
 '28',
 '61',
 '47',
 '1',
 '12',
 '7',
 '14',
 '58',
 '10',
 '16',
 '54',
 '14',
 '11',
 '10',
 '13',
 '22',
 '1',
 '5',
 '1',
 '43',
 '45',
 '4',
 '18',
 '7',
 '20',
 '12',
 '3',
 '7',
 '4',
 '1',
 '28',
 '3',
 '19',
 '29',
 '5',
 '25',
 '41',
 '41',
 '1',
 '3',
 '10',
 '4',
 '3',
 '10',
 '7',
 '3',
 '6',
 '1',
 '3',
 '1',
 '10',
 '2',
 '19',
 '15',
 '5',
 '3',
 '8',
 '10',
 '17',
 '6',
 '3',
 '11',
 '7',
 '1',
 '1',
 '16',
 '5',
 '3',
 '12',
 '14',
 '1',
 '2',
 '3',
 '9',
 '6',
 '14',
 '2',
 '16',
 '7',
 '4',
 '8',
 '1',
 '10',
 '2',
 '1',
 '11',
 '1',
 '1']

Q 4

In [1]:

import selenium
import pandas as pd
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.by import By
import warnings
warnings.filterwarnings('ignore')
import requests
from selenium.common.exceptions import StaleElementReferenceException,NoSuchElementException
import time

In [2]:
driver=webdriver.Chrome(r"C:\Users\Jigar\Downloads\chromedriver_win32")

In [3]:
driver.get(" https://github.com/")

In [11]:
Repository_title=[]

In [12]:
strat=0
end=1
for page in range(start,end):
    RT=driver.find_elements(By.XPATH,'//h2[@class="h3 lh-condensed"]')
    for i in RT:
        Repository_title.append(i.text)

In [13]:
Repository_title

['XingangPan / DragGAN',
 'THUDM / ChatGLM2-6B',
 'CASIA-IVA-Lab / FastSAM',
 'ramonvc / freegpt-webui',
 'embedchain / embedchain',
 'spacedriveapp / spacedrive',
 'xitanggg / open-resume',
 'papers-we-love / papers-we-love',
 'sadmann7 / skateshop',
 'microsoft / Web-Dev-For-Beginners',
 'sb-ocr / diy-spacemouse',
 'THUDM / ChatGLM-6B',
 'SizheAn / PanoHead',
 'PlexPt / awesome-chatgpt-prompts-zh',
 'firstcontributions / first-contributions',
 'actualbudget / actual',
 'xtekky / gpt4free',
 'sveltejs / svelte',
 'Zeqiang-Lai / DragGAN',
 'OpenDriveLab / UniAD',
 'qgis / QGIS',
 'chat2db / Chat2DB',
 'Kanaries / pygwalker',
 'ggerganov / ggml',
 'StanGirard / quivr']

In [14]:
Repository_description=[]

In [15]:
strat=0
end=1
for page in range(start,end):
    RD=driver.find_elements(By.XPATH,'//p[@class="col-9 color-fg-muted my-1 pr-4"]')
    for i in RD:
        Repository_description.append(i.text)

In [16]:
Repository_description

['Official Code for DragGAN (SIGGRAPH 2023)',
 'ChatGLM2-6B: An Open Bilingual Chat LLM | 开源双语对话语言模型',
 'Fast Segment Anything',
 'GPT 3.5/4 with a Chat Web UI. No API key required.',
 'Framework to easily create LLM powered bots over any dataset.',
 'Spacedrive is an open source cross-platform file explorer, powered by a virtual distributed filesystem written in Rust.',
 'OpenResume is a powerful open-source resume builder and resume parser. https://open-resume.com/',
 'Papers from the computer science community to read and discuss.',
 'An open source e-commerce skateshop build with everything new in Next.js 13.',
 '24 Lessons, 12 Weeks, Get Started as a Web Developer',
 'A DIY navigation device for Fusion360',
 'ChatGLM-6B: An Open Bilingual Dialogue Language Model | 开源双语对话语言模型',
 'Code Repository for CVPR 2023 Paper "PanoHead: Geometry-Aware 3D Full-Head Synthesis in 360 degree"',
 'ChatGPT 中文调教指南。各种场景使用指南。学习怎么让它听你的话。',
 '🚀✨ Help beginners to contribute to open source projects',
 'A local-first personal finance system',
 'The official gpt4free repository | various collection of powerful language models',
 'Cybernetically enhanced web apps',
 'Unofficial Implementation of DragGAN - "Drag Your GAN: Interactive Point-based Manipulation on the Generative Image Manifold" （DragGAN 全功能实现，在线Demo，本地部署试用，代码、模型已全部开源，支持Windows, macOS, Linux）',
 '[CVPR 2023 Best Paper] Planning-oriented Autonomous Driving',
 'QGIS is a free, open source, cross platform (lin/win/mac) geographical information system (GIS)',
 '🔥 🔥 🔥 An intelligent and versatile general-purpose SQL client and reporting tool for databases which integrates ChatGPT capabilities.(智能的通用数据库SQL客户端和报表工具)',
 'PyGWalker: Turn your pandas dataframe into a Tableau-style User Interface for visual analysis',
 'Tensor library for machine learning',
 '🧠 Dump all your files and thoughts into your private GenerativeAI Second Brain and chat with it 🧠']

In [17]:
 Contributors_count=[]

In [18]:
strat=0
end=1
for page in range(start,end):
    CC=driver.find_elements(By.XPATH,'//a[@class="Link--muted d-inline-block mr-3"]')
    for i in CC:
        Contributors_count.append(i.text)

In [19]:
Contributors_count

['23,841',
 '2,058',
 '4,498',
 '481',
 '3,414',
 '568',
 '953',
 '292',
 '2,301',
 '348',
 '20,190',
 '668',
 '1,615',
 '80',
 '74,125',
 '5,451',
 '2,774',
 '440',
 '71,410',
 '11,239',
 '395',
 '61',
 '30,080',
 '3,943',
 '820',
 '94',
 '40,427',
 '12,640',
 '34,632',
 '61,463',
 '6,976',
 '585',
 '41,514',
 '10,744',
 '70,305',
 '3,866',
 '4,498',
 '477',
 '1,655',
 '175',
 '7,792',
 '2,621',
 '2,014',
 '359',
 '6,288',
 '224',
 '4,906',
 '448',
 '8,795',
 '1,085']

In [20]:
 Language_used=[]

In [21]:
strat=0
end=1
for page in range(start,end):
    LU=driver.find_elements(By.XPATH,'//span[@class="d-inline-block ml-0 mr-3"]/span[2]')
    for i in LU:
        Language_used.append(i.text)

In [22]:
Language_used

['Python',
 'Python',
 'Python',
 'Python',
 'Python',
 'Rust',
 'TypeScript',
 'Shell',
 'TypeScript',
 'JavaScript',
 'C++',
 'Python',
 'Python',
 'JavaScript',
 'Python',
 'JavaScript',
 'Python',
 'Python',
 'C++',
 'Java',
 'Python',
 'C',
 'TypeScript']

Q 3

In [1]:
import selenium
import pandas as pd
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.by import By
import warnings
warnings.filterwarnings('ignore')
import requests
from selenium.common.exceptions import StaleElementReferenceException,NoSuchElementException
import time

In [2]:
driver=webdriver.Chrome(r"C:\Users\Jigar\Downloads\chromedriver_win32")

In [3]:
driver.get("https://www.statisticstimes.com/")

In [4]:
link=driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/div[2]/button')
link.send_keys("Economy")

In [5]:
search=driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/div[2]/button/i')
search.click()
time.sleep(2)

In [6]:
india_link=driver.find_element(By.XPATH,'//div[@class="dropdown-content"]/a[3]')
india_link.send_keys("India state")

In [7]:
search.link=driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/div[2]')
search.link.click()
time.sleep(2)

In [8]:
Rank=[]

In [20]:

start=0
end=1
for page in range(start,end):
    RK=driver.find_elements(By.XPATH,'//table[@class="display dataTable"]/tbody/tr/td[1]')
    for i in RK:
        Rank.append(i.text)

In [21]:
Rank

['1',
 'Maharashtra',
 '-',
 '2,632,792',
 '13.94%',
 '399.921',
 '-',
 '2,039,074',
 '2',
 'Tamil Nadu',
 '1,845,853',
 '1,630,208',
 '8.63%',
 '247.629',
 '1,312,929',
 '1,215,307',
 '3',
 'Uttar Pradesh',
 '1,687,818',
 '1,584,764',
 '8.39%',
 '240.726',
 '1,166,817',
 '1,123,982',
 '4',
 'Gujarat',
 '-',
 '1,502,899',
 '7.96%',
 '228.290',
 '-',
 '1,186,379',
 '5',
 'Karnataka',
 '1,631,977',
 '1,493,127',
 '7.91%',
 '226.806',
 '1,156,039',
 '1,091,077',
 '6',
 'West Bengal',
 '1,253,832',
 '1,089,898',
 '5.77%',
 '165.556',
 '793,223',
 '739,525',
 '7',
 'Rajasthan',
 '1,020,989',
 '942,586',
 '4.99%',
 '143.179',
 '711,627',
 '677,428',
 '8',
 'Andhra Pradesh',
 '972,782',
 '862,957',
 '4.57%',
 '131.083',
 '672,018',
 '621,301',
 '9',
 'Telangana',
 '969,604',
 '861,031',
 '4.56%',
 '130.791',
 '663,258',
 '612,828',
 '10',
 'Madhya Pradesh',
 '906,672',
 '809,592',
 '4.29%',
 '122.977',
 '561,801',
 '522,009',
 '11',
 'Kerala',
 '-',
 '781,653',
 '4.14%',
 '118.733',
 '-',
 '559,412',
 '12',
 'Delhi',
 '856,112',
 '774,870',
 '4.10%',
 '117.703',
 '634,408',
 '590,569',
 '13',
 'Haryana',
 '831,610',
 '734,163',
 '3.89%',
 '111.519',
 '572,240',
 '531,085',
 '14',
 'Bihar',
 '611,804',
 '530,363',
 '2.81%',
 '80.562',
 '414,977',
 '375,651',
 '15',
 'Punjab',
 '574,760',
 '526,376',
 '2.79%',
 '79.957',
 '418,868',
 '397,669',
 '16',
 'Odisha',
 '521,275',
 '487,805',
 '2.58%',
 '74.098',
 '396,499',
 '376,877',
 '17',
 'Assam',
 '-',
 '315,881',
 '1.67%',
 '47.982',
 '-',
 '234,048',
 '18',
 'Chhattisgarh',
 '329,180',
 '304,063',
 '1.61%',
 '46.187',
 '243,477',
 '231,182',
 '19',
 'Jharkhand',
 '328,598',
 '297,204',
 '1.57%',
 '45.145',
 '240,036',
 '224,986',
 '20',
 'Uttarakhand',
 '-',
 '245,895',
 '1.30%',
 '37.351',
 '-',
 '193,273',
 '21',
 'Jammu & Kashmir',
 '-',
 '155,956',
 '0.83%',
 '23.690',
 '-',
 '112,755',
 '22',
 'Himachal Pradesh',
 '165,472',
 '153,845',
 '0.81%',
 '23.369',
 '124,403',
 '117,851',
 '23',
 'Goa',
 '80,449',
 '73,170',
 '0.39%',
 '11.115',
 '63,408',
 '57,787',
 '24',
 'Tripura',
 '55,984',
 '49,845',
 '0.26%',
 '7.571',
 '40,583',
 '36,963',
 '25',
 'Chandigarh',
 '-',
 '42,114',
 '0.22%',
 '6.397',
 '-',
 '31,192',
 '26',
 'Puducherry',
 '38,253',
 '34,433',
 '0.18%',
 '5.230',
 '25,093',
 '23,013',
 '27',
 'Meghalaya',
 '36,572',
 '33,481',
 '0.18%',
 '5.086',
 '26,695',
 '24,682',
 '28',
 'Sikkim',
 '32,496',
 '28,723',
 '0.15%',
 '4.363',
 '20,017',
 '18,722',
 '29',
 'Manipur',
 '31,790',
 '27,870',
 '0.15%',
 '4.233',
 '20,673',
 '19,300',
 '30',
 'Nagaland',
 '-',
 '27,283',
 '0.14%',
 '4.144',
 '-',
 '17,647',
 '31',
 'Arunachal Pradesh',
 '-',
 '24,603',
 '0.13%',
 '3.737',
 '-',
 '16,676',
 '32',
 'Mizoram',
 '26,503',
 '22,287',
 '0.12%',
 '3.385',
 '18,797',
 '16,478',
 '33',
 'Andaman & Nicobar Islands',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '1',
 'Maharashtra',
 '-',
 '2,332,992',
 '13.97%',
 '-',
 '1,794,123',
 '2',
 'Tamil Nadu',
 '1,659,210',
 '1,465,361',
 '8.77%',
 '1,167,776',
 '1,079,894',
 '3',
 'Uttar Pradesh',
 '1,495,758',
 '1,404,761',
 '8.41%',
 '1,015,735',
 '979,159',
 '4',
 'Karnataka',
 '1,476,983',
 '1,351,553',
 '8.09%',
 '1,035,131',
 '976,948',
 '5',
 'Gujarat',
 '-',
 '1,322,936',
 '7.92%',
 '-',
 '1,036,859',
 '6',
 'West Bengal',
 '1,150,711',
 '995,502',
 '5.96%',
 '713,376',
 '662,432',
 '7',
 'Rajasthan',
 '916,014',
 '845,247',
 '5.06%',
 '630,693',
 '600,433',
 '8',
 'Telangana',
 '881,873',
 '782,370',
 '4.68%',
 '594,806',
 '549,481',
 '9',
 'Andhra Pradesh',
 '875,429',
 '776,140',
 '4.65%',
 '595,605',
 '550,584',
 '10',
 'Madhya Pradesh',
 '827,019',
 '737,156',
 '4.41%',
 '496,798',
 '461,903',
 '11',
 'Kerala',
 '-',
 '707,542',
 '4.24%',
 '-',
 '513,322',
 '12',
 'Delhi',
 '779,647',
 '704,529',
 '4.22%',
 '568,265',
 '529,739',
 '13',
 'Haryana',
 '755,790',
 '666,075',
 '3.99%',
 '514,983',
 '477,834',
 '14',
 'Bihar',
 '562,710',
 '486,776',
 '2.91%',
 '377,276',
 '340,512',
 '15',
 'Punjab',
 '517,521',
 '472,506',
 '2.83%',
 '374,015',
 '354,830',
 '16',
 'Odisha',
 '457,757',
 '428,031',
 '2.56%',
 '344,437',
 '327,805',
 '17',
 'Assam',
 '-',
 '282,782',
 '1.69%',
 '-',
 '207,193',
 '18',
 'Jharkhand',
 '301,242',
 '271,990',
 '1.63%',
 '218,232',
 '204,423',
 '19',
 'Chhattisgarh',
 '288,041',
 '266,537',
 '1.60%',
 '210,837',
 '200,453',
 '20',
 'Uttarakhand',
 '-',
 '221,871',
 '1.33%',
 '-',
 '173,211',
 '21',
 'Himachal Pradesh',
 '143,063',
 '133,303',
 '0.80%',
 '107,171',
 '101,534',
 '22',
 'Jammu & Kashmir',
 '-',
 '129,877',
 '0.78%',
 '-',
 '91,666',
 '23',
 'Goa',
 '72,181',
 '66,060',
 '0.40%',
 '56,810',
 '51,878',
 '24',
 'Tripura',
 '50,227',
 '44,835',
 '0.27%',
 '35,980',
 '32,830',
 '25',
 'Chandigarh',
 '-',
 '37,571',
 '0.22%',
 '-',
 '27,565',
 '26',
 'Puducherry',
 '34,823',
 '31,415',
 '0.19%',
 '22,291',
 '20,534',
 '27',
 'Meghalaya',
 '32,833',
 '29,544',
 '0.18%',
 '23,564',
 '21,779',
 '28',
 'Manipur',
 '29,148',
 '25,323',
 '0.15%',
 '18,549',
 '17,228',
 '29',
 'Sikkim',
 '28,391',
 '25,141',
 '0.15%',
 '17,060',
 '15,972',
 '30',
 'Nagaland',
 '-',
 '24,534',
 '0.15%',
 '-',
 '15,381',
 '31',
 'Arunachal Pradesh',
 '-',
 '22,488',
 '0.13%',
 '-',
 '15,013',
 '32',
 'Mizoram',
 '24,424',
 '20,947',
 '0.13%',
 '17,797',
 '15,372',
 '33',
 'Andaman & Nicobar Islands',
 '-',
 '-',
 '-',
 '-',
 '-',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '1',
 '3',
 '5',
 '7',
 '9',
 '11',
 '13',
 '15',
 '17',
 '19',
 '21',
 '23',
 '25',
 '27',
 '29',
 '31',
 '33',
 '1',
 '3',
 '5',
 '7',
 '9',
 '11',
 '13',
 '15',
 '17',
 '19',
 '21',
 '23',
 '25',
 '27',
 '29',
 '31',
 '33',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33']

In [17]:
State=[]

In [18]:
start=0
end=1
for page in range(start,end):
    ST=driver.find_elements(By.XPATH,'//table[@class="display dataTable"]/tbody/tr/td[2]')
    for i in ST:
        State.append(i.text)

In [19]:
State

['Maharashtra',
 'Tamil Nadu',
 'Uttar Pradesh',
 'Gujarat',
 'Karnataka',
 'West Bengal',
 'Rajasthan',
 'Andhra Pradesh',
 'Telangana',
 'Madhya Pradesh',
 'Kerala',
 'Delhi',
 'Haryana',
 'Bihar',
 'Punjab',
 'Odisha',
 'Assam',
 'Chhattisgarh',
 'Jharkhand',
 'Uttarakhand',
 'Jammu & Kashmir',
 'Himachal Pradesh',
 'Goa',
 'Tripura',
 'Chandigarh',
 'Puducherry',
 'Meghalaya',
 'Sikkim',
 'Manipur',
 'Nagaland',
 'Arunachal Pradesh',
 'Mizoram',
 'Andaman & Nicobar Islands',
 'Maharashtra',
 'Tamil Nadu',
 'Uttar Pradesh',
 'Karnataka',
 'Gujarat',
 'West Bengal',
 'Rajasthan',
 'Telangana',
 'Andhra Pradesh',
 'Madhya Pradesh',
 'Kerala',
 'Delhi',
 'Haryana',
 'Bihar',
 'Punjab',
 'Odisha',
 'Assam',
 'Jharkhand',
 'Chhattisgarh',
 'Uttarakhand',
 'Himachal Pradesh',
 'Jammu & Kashmir',
 'Goa',
 'Tripura',
 'Chandigarh',
 'Puducherry',
 'Meghalaya',
 'Manipur',
 'Sikkim',
 'Nagaland',
 'Arunachal Pradesh',
 'Mizoram',
 'Andaman & Nicobar Islands']

In [22]:
GSDP_CP=[]

In [23]:
start=0
end=1
for page in range(start,end):
    GC=driver.find_elements(By.XPATH,'//table[@class="display dataTable"]/tbody/tr/td[3]')
    for i in GC:
        GSDP_CP.append(i.text)

In [24]:
GSDP_CP

['-',
 '1,845,853',
 '1,687,818',
 '-',
 '1,631,977',
 '1,253,832',
 '1,020,989',
 '972,782',
 '969,604',
 '906,672',
 '-',
 '856,112',
 '831,610',
 '611,804',
 '574,760',
 '521,275',
 '-',
 '329,180',
 '328,598',
 '-',
 '-',
 '165,472',
 '80,449',
 '55,984',
 '-',
 '38,253',
 '36,572',
 '32,496',
 '31,790',
 '-',
 '-',
 '26,503',
 '-',
 '-',
 '1,659,210',
 '1,495,758',
 '1,476,983',
 '-',
 '1,150,711',
 '916,014',
 '881,873',
 '875,429',
 '827,019',
 '-',
 '779,647',
 '755,790',
 '562,710',
 '517,521',
 '457,757',
 '-',
 '301,242',
 '288,041',
 '-',
 '143,063',
 '-',
 '72,181',
 '50,227',
 '-',
 '34,823',
 '32,833',
 '29,148',
 '28,391',
 '-',
 '-',
 '24,424',
 '-']

In [25]:
GSDP_CP2=[]

In [32]:
start=0
end=1
for page in range(start,end):
    GC=driver.find_elements(By.XPATH,'//table[@class="display dataTable"]/tbody/tr/td[4]')
    for i in GC:
        GSDP_CP2.append(i.text)

In [33]:
GSDP_CP2

['2,632,792',
 '1,630,208',
 '1,584,764',
 '1,502,899',
 '1,493,127',
 '1,089,898',
 '942,586',
 '862,957',
 '861,031',
 '809,592',
 '781,653',
 '774,870',
 '734,163',
 '530,363',
 '526,376',
 '487,805',
 '315,881',
 '304,063',
 '297,204',
 '245,895',
 '155,956',
 '153,845',
 '73,170',
 '49,845',
 '42,114',
 '34,433',
 '33,481',
 '28,723',
 '27,870',
 '27,283',
 '24,603',
 '22,287',
 '-',
 '2,332,992',
 '1,465,361',
 '1,404,761',
 '1,351,553',
 '1,322,936',
 '995,502',
 '845,247',
 '782,370',
 '776,140',
 '737,156',
 '707,542',
 '704,529',
 '666,075',
 '486,776',
 '472,506',
 '428,031',
 '282,782',
 '271,990',
 '266,537',
 '221,871',
 '133,303',
 '129,877',
 '66,060',
 '44,835',
 '37,571',
 '31,415',
 '29,544',
 '25,323',
 '25,141',
 '24,534',
 '22,488',
 '20,947',
 '-']

In [31]:
Share=[]

In [34]:
start=0
end=1
for page in range(start,end):
    SH=driver.find_elements(By.XPATH,'//table[@class="display dataTable"]/tbody/tr/td[5]')
    for i in SH:
        Share.append(i.text)

In [35]:
Share

['13.94%',
 '8.63%',
 '8.39%',
 '7.96%',
 '7.91%',
 '5.77%',
 '4.99%',
 '4.57%',
 '4.56%',
 '4.29%',
 '4.14%',
 '4.10%',
 '3.89%',
 '2.81%',
 '2.79%',
 '2.58%',
 '1.67%',
 '1.61%',
 '1.57%',
 '1.30%',
 '0.83%',
 '0.81%',
 '0.39%',
 '0.26%',
 '0.22%',
 '0.18%',
 '0.18%',
 '0.15%',
 '0.15%',
 '0.14%',
 '0.13%',
 '0.12%',
 '-',
 '13.97%',
 '8.77%',
 '8.41%',
 '8.09%',
 '7.92%',
 '5.96%',
 '5.06%',
 '4.68%',
 '4.65%',
 '4.41%',
 '4.24%',
 '4.22%',
 '3.99%',
 '2.91%',
 '2.83%',
 '2.56%',
 '1.69%',
 '1.63%',
 '1.60%',
 '1.33%',
 '0.80%',
 '0.78%',
 '0.40%',
 '0.27%',
 '0.22%',
 '0.19%',
 '0.18%',
 '0.15%',
 '0.15%',
 '0.15%',
 '0.13%',
 '0.13%',
 '-']

In [36]:
GDP=[]

In [37]:
start=0
end=1
for page in range(start,end):
    dp=driver.find_elements(By.XPATH,'//table[@class="display dataTable"]/tbody/tr/td[6]')
    for i in dp:
        GDP.append(i.text)

In [38]:
GDP

['399.921',
 '247.629',
 '240.726',
 '228.290',
 '226.806',
 '165.556',
 '143.179',
 '131.083',
 '130.791',
 '122.977',
 '118.733',
 '117.703',
 '111.519',
 '80.562',
 '79.957',
 '74.098',
 '47.982',
 '46.187',
 '45.145',
 '37.351',
 '23.690',
 '23.369',
 '11.115',
 '7.571',
 '6.397',
 '5.230',
 '5.086',
 '4.363',
 '4.233',
 '4.144',
 '3.737',
 '3.385',
 '-',
 '-',
 '1,167,776',
 '1,015,735',
 '1,035,131',
 '-',
 '713,376',
 '630,693',
 '594,806',
 '595,605',
 '496,798',
 '-',
 '568,265',
 '514,983',
 '377,276',
 '374,015',
 '344,437',
 '-',
 '218,232',
 '210,837',
 '-',
 '107,171',
 '-',
 '56,810',
 '35,980',
 '-',
 '22,291',
 '23,564',
 '18,549',
 '17,060',
 '-',
 '-',
 '17,797',
 '-']

Q 2

In [39]:

import selenium
import pandas as pd
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.by import By
import warnings
warnings.filterwarnings('ignore')
import requests
from selenium.common.exceptions import StaleElementReferenceException,NoSuchElementException
import time

In [40]:
driver=webdriver.Chrome(r"C:\Users\Jigar\Downloads\chromedriver_win32")

In [42]:
driver.get("https://www.bcci.tv/")

In [43]:
link=driver.find_element(By.XPATH,'/html/body/nav/div[1]/div[2]/ul[1]/li[2]/a')
link.send_keys("International")

In [44]:
search=driver.find_element(By.XPATH,'/html/body/nav/div[1]/div[2]/ul[2]/li/div/button/span')
search.click()
time.sleep(2)

In [45]:
Match_title=[]

In [60]:
start=0
end=1
for page in range(start,end):
    MT=driver.find_elements(By.XPATH,'//span[@class="matchOrderText ng-binding ng-scope"]')
    for i in MT:
        Match_title.append(i.text)

In [61]:
Match_title

['1st T20I -',
 '2nd T20I -',
 '1st Test -',
 '3rd T20I -',
 '1st ODI -',
 '2nd ODI -',
 '2nd Test -',
 '3rd ODI -',
 '1st T20I -',
 '2nd T20I -',
 '1st Test -',
 '3rd T20I -',
 '1st ODI -',
 '2nd ODI -',
 '2nd Test -',
 '3rd ODI -',
 '1st ODI -',
 '2nd ODI -',
 '3rd ODI -',
 '1st T20I -',
 '2nd T20I -',
 '3rd T20I -',
 '4th T20I -',
 '5th T20I -']

In [48]:
Series=[]

In [49]:
start=0
end=1
for page in range(start,end):
    Sr=driver.find_elements(By.XPATH,'//h5[@class="match-tournament-name ng-binding"]')
    for i in Sr:
        Series.append(i.text)

In [50]:
Series

['INDIA WOMEN TOUR OF BANGLADESH 2023',
 'INDIA WOMEN TOUR OF BANGLADESH 2023',
 'INDIA TOUR OF WEST INDIES 2023',
 'INDIA WOMEN TOUR OF BANGLADESH 2023',
 'INDIA WOMEN TOUR OF BANGLADESH 2023',
 'INDIA WOMEN TOUR OF BANGLADESH 2023',
 'INDIA TOUR OF WEST INDIES 2023',
 'INDIA WOMEN TOUR OF BANGLADESH 2023',
 'INDIA TOUR OF WEST INDIES 2023',
 'INDIA TOUR OF WEST INDIES 2023',
 'INDIA TOUR OF WEST INDIES 2023',
 'INDIA TOUR OF WEST INDIES 2023',
 'INDIA TOUR OF WEST INDIES 2023',
 'INDIA TOUR OF WEST INDIES 2023',
 'INDIA TOUR OF WEST INDIES 2023',
 'INDIA TOUR OF WEST INDIES 2023']

In [51]:
Place=[]

In [52]:
start=0
end=1
for page in range(start,end):
    Pl=driver.find_elements(By.XPATH,'//span[@class="ng-binding ng-scope"]')
    for i in Pl:
        Place.append(i.text)

In [53]:
Place

['Shere Bangla National Stadium, Mirpur,',
 'Shere Bangla National Stadium, Mirpur,',
 'Windsor Park,',
 'Shere Bangla National Stadium, Mirpur,',
 'Shere Bangla National Stadium, Mirpur,',
 'Shere Bangla National Stadium, Mirpur,',
 "Queen's Park Oval,",
 'Shere Bangla National Stadium, Mirpur,',
 'Kensington Oval,',
 'Kensington Oval,',
 'Brian Lara Stadium,',
 'Brian Lara Stadium,',
 'National Stadium,',
 'National Stadium,',
 'Central Broward Regional Park Stadium Turf Ground,',
 'Central Broward Regional Park Stadium Turf Ground,']

In [54]:
Date=[]

In [55]:
start=0
end=1
for page in range(start,end):
    dt=driver.find_elements(By.XPATH,'//div[@class="match-dates ng-binding"]')
    for i in dt:
        Date.append(i.text)

In [56]:
Date

['9 JUL 2023',
 '11 JUL 2023',
 '12 JUL 2023',
 '13 JUL 2023',
 '16 JUL 2023',
 '19 JUL 2023',
 '20 JUL 2023',
 '22 JUL 2023',
 '27 JUL 2023',
 '29 JUL 2023',
 '1 AUG 2023',
 '3 AUG 2023',
 '6 AUG 2023',
 '8 AUG 2023',
 '12 AUG 2023',
 '13 AUG 2023']

In [57]:
Time=[]

In [58]:
start=0
end=1
for page in range(start,end):
    tm=driver.find_elements(By.XPATH,'//div[@class="match-time no-margin ng-binding"]')
    for i in tm:
        Time.append(i.text)

In [59]:
Time

['1:30 PM IST',
 '1:30 PM IST',
 '7:30 PM IST',
 '1:30 PM IST',
 '9:00 AM IST',
 '9:00 AM IST',
 '7:30 PM IST',
 '9:00 AM IST',
 '7:00 PM IST',
 '7:00 PM IST',
 '7:00 PM IST',
 '8:00 PM IST',
 '8:00 PM IST',
 '8:00 PM IST',
 '8:00 PM IST',
 '8:00 PM IST']

Q 1

In [62]:
import selenium
import pandas as pd
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.by import By
import warnings
warnings.filterwarnings('ignore')
import requests
from selenium.common.exceptions import StaleElementReferenceException,NoSuchElementException
import time

In [63]:
driver=webdriver.Chrome(r"C:\Users\Jigar\Downloads\chromedriver_win32")

In [64]:
driver.get("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos")

In [65]:
Rank=[]

In [66]:

start=0
end=1
for page in range(start,end):
    rn=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[1]')
    for i in rn:
        Rank.append(i.text)

In [67]:
Rank

['1.',
 '2.',
 '3.',
 '4.',
 '5.',
 '6.',
 '7.',
 '8.',
 '9.',
 '10.',
 '11.',
 '12.',
 '13.',
 '14.',
 '15.',
 '16.',
 '17.',
 '18.',
 '19.',
 '20.',
 '21.',
 '22.',
 '23.',
 '24.',
 '25.',
 '26.',
 '27.',
 '28.',
 '29.',
 '30.',
 '"Baby Shark Dance"[6]',
 '"Despacito"[9]',
 '"See You Again"[21]',
 '"Gangnam Style"⁂[30]',
 '"Baby"*[66]',
 '"Bad Romance"[70]',
 '"Charlie Bit My Finger"‡[74]',
 '"Evolution of Dance"[77]',
 '"Girlfriend"‡[79][80]',
 '"Evolution of Dance"[77]',
 '"Music Is My Hot Hot Sex"‡[84]',
 '"Evolution of Dance"*[77]',
 '"Pokémon Theme Music Video"‡[90]',
 '"Myspace – The Movie"‡[95][96]',
 '"Phony Photo Booth"‡[99]',
 '"The Chronic of Narnia Rap"‡[101]',
 '"Cross Bar"‡[103]',
 '"Ronaldinho: Touch of Gold"‡*[105]',
 '"I/O Brush"‡*[108]',
 '"Me at the zoo"[111]']

In [68]:
Name=[]

In [69]:
start=0
end=1
for page in range(start,end):
    nm=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[2]/a')
    for i in nm:
        Name.append(i.text)

In [70]:
Name

['Baby Shark Dance',
 'Despacito',
 'Johny Johny Yes Papa',
 'Shape of You',
 'See You Again',
 'Wheels on the Bus',
 'Uptown Funk',
 'Gangnam Style',
 'Dame Tu Cosita',
 'Axel F',
 'Sugar',
 'Roar',
 'Counting Stars',
 'Sorry',
 'Baa Baa Black Sheep',
 'Thinking Out Loud',
 'Waka Waka (This Time for Africa)',
 'Dark Horse',
 'Faded',
 'Perfect',
 'Let Her Go',
 'Girls Like You',
 'Lean On',
 'Bailando',
 "Pinkfong Baby Shark - Kids' Songs & Stories",
 'Luis Fonsi',
 'Wiz Khalifa',
 'Psy',
 'Justin Bieber',
 'Lady Gaga',
 'Judson Laipply',
 'RCA Records',
 'Judson Laipply',
 'Judson Laipply',
 'Smosh',
 'Nikesoccer',
 'jawed']

In [71]:
Artist=[]

In [74]:
start=0
end=1
for page in range(start,end):
    ar=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[3]')
    for i in ar:
        Artist.append(i.text)

In [75]:
Artist

["Pinkfong Baby Shark - Kids' Songs & Stories",
 'Luis Fonsi',
 'LooLoo Kids',
 'Cocomelon – Nursery Rhymes',
 'Ed Sheeran',
 'Wiz Khalifa',
 'ChuChu TV',
 'Cocomelon – Nursery Rhymes',
 'Mark Ronson',
 'Miroshka TV',
 'Psy',
 'Get Movies',
 'El Chombo',
 'Crazy Frog',
 'Maroon 5',
 'Katy Perry',
 'OneRepublic',
 'Justin Bieber',
 'Cocomelon – Nursery Rhymes',
 'Ed Sheeran',
 'Shakira',
 'Katy Perry',
 'Jingle Toons',
 'Alan Walker',
 'Ed Sheeran',
 'Passenger',
 'Maroon 5',
 'Kiddiestv Hindi – Nursery Rhymes & Kids Songs',
 'Major Lazer',
 'Enrique Iglesias',
 '7,046,700,000',
 '2,993,700,000',
 '2,894,000,000',
 '803,700,000',
 '245,400,000',
 '178,400,000',
 '128,900,000',
 '118,900,000',
 '92,600,000',
 '78,400,000',
 '76,600,000',
 '10,600,000',
 '4,300,000',
 '2,700,000',
 '3,400,000',
 '2,300,000',
 '1,000,000',
 '255,000',
 '247,000',
 '1']

In [76]:
Upload_date=[]

In [87]:
start=0
end=1
for page in range(start,end):
    ud=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[5]')
    for i in ud:
        Upload_date.append(i.text)

In [88]:
Upload_date

['[A]',
 '[B]',
 '',
 '',
 '[C]',
 '[D]',
 '',
 '',
 '',
 '',
 '[E]',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '1600',
 '206',
 '826',
 '134',
 '149',
 '143',
 '887',
 '1062',
 '508',
 '651',
 '327',
 '16',
 '105',
 '18',
 '50',
 '22',
 '50',
 '10',
 '24',
 '0',
 'June 17, 2016',
 'January 12, 2017',
 'October 8, 2016',
 'May 2, 2018',
 'January 30, 2017',
 'April 6, 2015',
 'March 6, 2014',
 'May 24, 2018',
 'November 19, 2014',
 'February 27, 2018',
 'July 15, 2012',
 'January 31, 2012',
 'April 5, 2018',
 'June 16, 2009',
 'January 14, 2015',
 'September 5, 2013',
 'May 31, 2013',
 'October 22, 2015',
 'June 25, 2018',
 'October 7, 2014',
 'June 4, 2010',
 'February 20, 2014',
 'June 14, 2018',
 'December 3, 2015',
 'November 9, 2017',
 'July 25, 2012',
 'May 31, 2018',
 'January 26, 2018',
 'March 22, 2015',
 'April 11, 2014',
 'November 2, 2020',
 'August 4, 2017',
 'July 10, 2017',
 'November 24, 2012',
 'July 16, 2010',
 'April 14, 2010',
 'October 25, 2009',
 'May 2, 2009',
 'July 17, 2008',
 'March 15, 2008',
 'March 1, 2008',
 'May 19, 2006',
 'March 12, 2006',
 'February 18, 2006',
 'January 21, 2006',
 'January 9, 2006',
 'December 10, 2005',
 'October 31, 2005',
 'October 29, 2005',
 'April 23, 2005',
 '967',
 '1,186',
 '25',
 '1,689',
 '862',
 '93',
 '171',
 '176',
 '289',
 '124',
 '14',
 '652',
 '68',
 '22',
 '28',
 '12',
 '30',
 '40',
 '2',
 '189',
 '12.85',
 '8.16',
 '6.70',
 '6.20',
 '6.00',
 '5.89',
 '5.30',
 '5.24',
 '4.92',
 '4.89',
 '4.80',
 '4.55',
 '4.35',
 '3.91',
 '3.87',
 '3.80',
 '3.79',
 '3.66',
 '3.64',
 '3.60',
 '3.59',
 '3.52',
 '3.48',
 '3.45',
 '3.45',
 '3.44',
 '3.42',
 '3.41',
 '3.38',
 '3.38',
 'June 17, 2016',
 'January 12, 2017',
 'April 6, 2015',
 'July 15, 2012',
 'February 19, 2010',
 'November 24, 2009',
 'May 22, 2007',
 'April 6, 2006',
 'February 27, 2007',
 'April 6, 2006',
 'April 9, 2007',
 'April 6, 2006',
 'November 28, 2005',
 'January 31, 2006',
 'December 1, 2005',
 'December 18, 2005',
 'October 21, 2005',
 'October 21, 2005',
 'October 5, 2005',
 'April 23, 2005',
 'June 17, 2016',
 'January 12, 2017',
 'October 8, 2016',
 'May 2, 2018',
 'January 30, 2017',
 'April 6, 2015',
 'March 6, 2014',
 'May 24, 2018',
 'November 19, 2014',
 'February 27, 2018',
 'July 15, 2012',
 'January 31, 2012',
 'April 5, 2018',
 'June 16, 2009',
 'January 14, 2015',
 'September 5, 2013',
 'May 31, 2013',
 'October 22, 2015',
 'June 25, 2018',
 'October 7, 2014',
 'June 4, 2010',
 'February 20, 2014',
 'June 14, 2018',
 'December 3, 2015',
 'November 9, 2017',
 'July 25, 2012',
 'May 31, 2018',
 'January 26, 2018',
 'March 22, 2015',
 'April 11, 2014',
 'November 2, 2020',
 'August 4, 2017',
 'July 10, 2017',
 'November 24, 2012',
 'July 16, 2010',
 'April 14, 2010',
 'October 25, 2009',
 'May 2, 2009',
 'July 17, 2008',
 'March 15, 2008',
 'March 1, 2008',
 'May 19, 2006',
 'March 12, 2006',
 'February 18, 2006',
 'January 21, 2006',
 'January 9, 2006',
 'December 10, 2005',
 'October 31, 2005',
 'October 29, 2005',
 'April 23, 2005']

In [89]:
views=[]

In [90]:
start=0
end=1
for page in range(start,end):
    vi=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[4]')
    for i in vi:
        views.append(i.text)

In [91]:
views

['12.85',
 '8.16',
 '6.70',
 '6.20',
 '6.00',
 '5.89',
 '5.30',
 '5.24',
 '4.92',
 '4.89',
 '4.80',
 '4.55',
 '4.35',
 '3.91',
 '3.87',
 '3.80',
 '3.79',
 '3.66',
 '3.64',
 '3.60',
 '3.59',
 '3.52',
 '3.48',
 '3.45',
 '3.45',
 '3.44',
 '3.42',
 '3.41',
 '3.38',
 '3.38',
 'June 17, 2016',
 'January 12, 2017',
 'April 6, 2015',
 'July 15, 2012',
 'February 19, 2010',
 'November 24, 2009',
 'May 22, 2007',
 'April 6, 2006',
 'February 27, 2007',
 'April 6, 2006',
 'April 9, 2007',
 'April 6, 2006',
 'November 28, 2005',
 'January 31, 2006',
 'December 1, 2005',
 'December 18, 2005',
 'October 21, 2005',
 'October 21, 2005',
 'October 5, 2005',
 'April 23, 2005']